AltBeacon/android-beacon-library

.gitignore, build.gradle, gradle.properties, gradle/artifactory.gradle, gradle/bintray.gradle, gradle/compile.gradle, gradle/credentials.gradle, gradle/publishing.gradle
You will need to add your bintray username and key to `$HOME/.gradle/gradle.properties` as `bintrayUser=userHere` and `bintrayKey=keyHere`
To publish to bintray (Release) run `gradlew bintrayUpload -Prelease` and run `gradlew artifactoryPublish` to publish a snapshot to artifactory.
@davidgyoung Let me know when you get signed up to bintray and I will get you all setup with the altbeacon organization and give you more info on how to publish to maven central.
=> Added tasks to be able to publish to bintray and artifactory

src/main/AndroidManifest.xml
Because the services are only used from this library, they don't have to be exported in the manifest. Prevents potential security issues.
Specifying `exported=false` on services without an `intent-filter` element isn't necessary as `false` is then the default in that case, but this makes it more explicit when people read the manifest.
=> Don't export services in AndroidManifest

build.gradle, gradle/credentials.gradle
No need to log into the bintray UI anymore.
Since my username and password won't work for this, I couldn't test, but this is very similar to other projects so I should work. Just need to add more values to your gradle.properties and run `gradlew bintrayRelease`.
Let me know if you have any issues.
=> Added ability to do all publishing from gradle

src/main/java/org/altbeacon/beacon/distance/DistanceConfigFetcher.java, src/main/java/org/altbeacon/beacon/distance/ModelSpecificDistanceCalculator.java
First: You've created a great library! Thank you for that.
A small issue I noted when I looked at the code. When the status code is `HTTP_MOVED_PERM` or `HTTP_SEE_OTHER`, it ignores the request count. This is because the `&&` has a higher operator precedence and therefore get evaluated before the `||` operators.
=> Fixed ignoring of http redirection limit

gradle.properties
This removes properties that are causing System properties to not be pulled in, and thus not being able to be set by CI or being about to be set from global gradle.properties.
If these are not set, the properties should now be set to empty strings in the credentials.gradle.
=> removed unused properties

src/main/java/org/altbeacon/beacon/service/BeaconService.java
This fixes issue #88 reported in #84 where a long-running AsyncTask in a the application code can stop detection of beacons.
=> Fix AsyncTask blocking beacon parsing

build.gradle, gradle/bintray.gradle, gradle/publishing.gradle
@davidgyoung You'll have to test this out with the next release to make sure it's working as expected, but moving the tar.gz upload into the bintray task fixes the snapshot publishing issue.
#93
=> Updated to use bintray plugin 1.0

src/main/java/org/altbeacon/beacon/distance/ModelSpecificDistanceCalculator.java, src/main/java/org/altbeacon/bluetooth/BluetoothCrashResolver.java
#89 changed one AsyncTask, but two others in the code. Those were left unchanged.
* Perform downloading of distance config file in AsyncTask also in a ThreadPool, so the download doesn't block other AsyncTasks.
* Removed AsyncTask for BluetoothCrashResolver since doInBackground was called directly, so it was actually called synchronously,
=> Also execute other AsyncTask in ThreadPool

src/main/java/org/altbeacon/beacon/BeaconManager.java, src/main/java/org/altbeacon/beacon/Region.java, src/test/java/org/altbeacon/beacon/RegionTest.java
I've changed the Region class to become immutable of instantiation. Therefore it is no longer needed to have a copy constructor or for the object to be cloneable.
Also fixed the constructor that supported custom length Identifier lists and let equals take into account the identifiers.
Maybe for the backwards compatibility it is better to bring back the public clone method, maybe in deprecated form? What do you think?
=> Changed Region to become immutable.

build.gradle
The classes in the <code>android.*</code> packages weren't clickable links in Javadoc. Now they are.
The <code>java.*</code> classes now link to the Android reference as well instead of the Oracle reference. The Android reference gives a better descriptions when developing for Android.
=> Fix links to Android classes in Javadoc

src/main/java/org/altbeacon/beacon/Beacon.java, src/main/java/org/altbeacon/beacon/BeaconParser.java, src/main/java/org/altbeacon/beacon/Identifier.java, src/test/java/org/altbeacon/beacon/IdentifierTest.java, src/test/java/org/altbeacon/beacon/SBeaconTest.java
Made the class immutable, so it is no longer necessary to copy the Identifier before returning it.
As discussed in #97 
A breaking change I noticed was that parsing a value in decimal format no longer retains leading zeros, as SBeaconTest shows. I don't think this matters much. This doesn't affect the hexadecimal format.
=> Changed Identifier class to work with a byte array instead of a String

src/main/java/org/altbeacon/beacon/BeaconManager.java
I investigated the problem I told before (#116). It seems like 94520a8 caused problem. I have fixed the problem (actually reverted code). Since, ConsumerInfo is not an immutable class, putting the same reference to the map after changing isConnected to true is unnecessary.
So, it could be in this way as well:
```
for (BeaconConsumer consumer : consumers.keySet()) {
Boolean alreadyConnected = consumers.get(consumer).isConnected;
if (!alreadyConnected) {
consumer.onBeaconServiceConnect();
ConsumerInfo consumerInfo = consumers.get(consumer);
consumerInfo.isConnected = true;
}
}
```
BTW, sorry for the last PR.
=> fixed ConcurrentModificationException on BeaconManager

documentation.md
Looks like Android Studio reference project is in main and Eclipse in a branch but these links were the other way around.
=> Fix links to sample projects.

src/main/java/org/altbeacon/beacon/BeaconTransmitter.java
This addresses issue #134, which appears to be blocking beacon transmission on Motorola devices.
=> Allow beacon transmission on Motorola devices

src/main/java/org/altbeacon/beacon/service/BeaconService.java
Fixes issue described in #140 where stopping ranging/monitoring can create a race condition causing a null pointer exception.
=> Protect against NPE in a race condition

src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScanner.java
This allows the service to restart itself if killed due to memory pressure.  Bug was reported in #154
=> Fix broken wakeup timer preventing service restart

src/main/java/org/altbeacon/beacon/service/BeaconService.java, src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScanner.java
Bug introduced in 2.1 keeps scans from stopping when a consumer is still bound to the service, but no regions are actively being monitored or ranged.  This would causes extra battery usage by scanning unnecessarily.
With this change, scanning stops as soon as the last monitored/ranged region stops being monitored/ranged.  This is the intended behavior, and that which existed prior to 2.1.
=> Fix bug where scanning does not stop when ranging stops.

src/main/java/org/altbeacon/beacon/Beacon.java, src/test/java/org/altbeacon/beacon/BeaconTest.java
Check to see if lists have already been wrapped as an unmodifiableList before re-wrapping them in the getter.  Fixes #185
=> Fix stackoverflow from re-wrapping collections

src/main/java/org/altbeacon/beacon/BeaconParser.java, src/test/java/org/altbeacon/beacon/BeaconParserTest.java, src/test/java/org/altbeacon/beacon/org/altbeacon/beacon/simulator/BeaconSimulatorTest.java
Add better protection against corrupted packets.  Before this change, when a BLE packet is received with the first few bytes matching a beacon format, but the PDU length being too short to pull out all the fields specified in the beacon layout, the thread that parses the packet will throw an unchecked exception causing a crash and, leading to a stack trace in the logs. 
This change will detect that the packet is malformed, and silently refuse to parse the packet.  If debug logging is enabled, it will log details about why it is too short.
Addresses #221
=> Better corrupted packet protection

src/main/java/org/altbeacon/beacon/service/BeaconService.java, src/test/java/org/altbeacon/beacon/service/BeaconServiceTest.java
Simple implementation to avoid maxing out the AsyncTask.THREAD_POOL_EXECUTOR by using it for scan processing threads
=> use a private executor to avoid starving the default queue

src/main/java/org/altbeacon/beacon/service/BeaconService.java
Protect against a NPE as described in #212
=> Protect Against NPE in Iteration

src/main/java/org/altbeacon/beacon/BeaconManager.java
This addresses the issue described here:
https://github.com/AltBeacon/android-beacon-library-reference/issues/10
Where all beacon consumers unbinding can leave the library in a background scanning state.
=> backgroundMode-> false after stopping service, so it starts back up in foreground mode

src/main/java/org/altbeacon/beacon/BeaconParser.java, src/test/java/org/altbeacon/beacon/AltBeaconParserTest.java, src/test/java/org/altbeacon/beacon/BeaconParserTest.java
- allow missing data fields
- if an AltBeacon parser fails, don't crash with NPE
=> Make parser more tolerant per #229

src/main/java/org/altbeacon/beacon/AltBeaconParser.java, src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScannerForLollipop.java, src/test/java/org/altbeacon/beacon/BeaconParserTest.java
A recent commit put into 2.3.0 and 2.3.1 inadvertently started using scan filters on Android 5.x devices in the foreground:
https://github.com/AltBeacon/android-beacon-library/commit/66f9698b194dcf389f514d567816477e8da7b47f#diff-cbe9383c235303f12aa05161f0ed907cR177
Normally this would be no problem, but in some cases the scan filters did not match some beacon types, including AltBeacons with manufacturer type codes of 0x00e0 (Google) and 0x004c (Apple).  These unexpected manufacturer codes did not match the filter, causing no detections of these beacons to happen at all.
This change reverts the change so no filters are active in the foreground.  However, beacon transmitters using these non-standard manufacturer codes for AltBeacons will still fail to match the filters in the background, …
=> Detect various AltBeacon manufacturers in the foreground

src/main/java/org/altbeacon/beacon/BeaconParser.java, src/main/java/org/altbeacon/bluetooth/BleAdvertisement.java, src/main/java/org/altbeacon/bluetooth/Pdu.java, src/test/java/org/altbeacon/beacon/AltBeaconParserTest.java, src/test/java/org/altbeacon/beacon/BeaconParserTest.java, src/test/java/org/altbeacon/beacon/GattBeaconTest.java
* Corrected the PDU length calculation was undercounting the length by one byte.  
* Added buffer overrun protection against overruns on BeaconParser layouts that go beyond the length of the actual PDU size.  By default, the `BeaconParserClass`now  has `allowPduOverflow` set to true, allowing malformed packets to be parsed.  This can be configured to false to enforce stricter compliance, but may result in ignoring beacons with malformed PDU lengths.
* Added utility for compressing/decompressing UriBeacon URLs.
=> Correct PDU length calculation and protect against overruns

src/main/java/org/altbeacon/beacon/BeaconParser.java, src/main/java/org/altbeacon/beacon/BeaconTransmitter.java, src/main/java/org/altbeacon/beacon/Identifier.java, src/test/java/org/altbeacon/beacon/BeaconTransmitterTest.java, src/test/java/org/altbeacon/beacon/IdentifierTest.java
* Expose parser service uuid to transmitter
* Fix endianness of service uuid
* Allow more flexibility in parsing identifiers and specifying lengths
=> Enable EddystoneTtransmission

src/main/java/org/altbeacon/beacon/BeaconParser.java, src/main/java/org/altbeacon/beacon/utils/UrlBeaconUrlCompressor.java, src/test/java/org/altbeacon/beacon/BeaconParserTest.java, src/test/java/org/altbeacon/beacon/utils/UrlBeaconUrlCompressorTest.java
Changes to make Eddystone URL transmitter work
* Allow variable length identifiers in transmitted advertisement
* Properly handle additional cases in URL compression/decompression
=> Eddystone url transmitter support

src/main/java/org/altbeacon/beacon/Identifier.java, src/test/java/org/altbeacon/beacon/IdentifierTest.java
This fixes a bug where ranging and monitoring for beacons with an Identiier.parse("0") fails.  The reason for the failure is that the parsing was being done as a hex number, assuming a one byte length identifier.  Treating it as an integer defaults it to two bytes, which will match AltBeacon major and minor values.
=> Parse "0" as an integer identifier

src/main/java/org/altbeacon/beacon/Beacon.java, src/main/java/org/altbeacon/beacon/Region.java, src/test/java/org/altbeacon/beacon/BeaconTest.java
There is a lurking NPE in `Beacon.hashCode()` if any `Identifier` element of `mIndentifiers` is `null`. The similar logic in `toString()` already takes care of this, so this pull request factors out that logic and reuses it.
While I was in the `Beacon` code, I also noticed some low-lying fruit (simplifications/optimizations), which I have included. And I have also included an easier-to-understand simplified version of the related Region.matchesBeacon().
=> Fix NPE in Beacon.hashCode(), along with some optimizations

src/main/java/org/altbeacon/beacon/utils/UrlBeaconUrlCompressor.java, src/test/java/org/altbeacon/beacon/utils/UrlBeaconUrlCompressorTest.java
1. Properly matches upper/mixed-case scheme, e. g. HTTP or HTTPS
2. Properly matches upper/mixed-case domain, e. g. CIRCLE8.NET
3. Properly matches upper/mixed-case WWW
4. Properly matches upper/mixed-case known TLDs, e. g. .COM
5. Properly _preserves_ case in path, e. g. `http://goo.gl/C2HC48`
Fixes #262.
=> Generalized URL compressor to handle upper-case URL components properly

src/main/java/org/altbeacon/beacon/Region.java, src/test/java/org/altbeacon/beacon/RegionTest.java
Prevent an IndexOutOfBoundsException when comparing a Region to a Beacon with fewer identifiers.  This would cause a crash when looking for a Region with three non-null identifiers and then encountering a beacon (such as Eddystone UID) that only has two identifiers.
=> Fix crash when region has more identifiers than beacon

src/main/java/org/altbeacon/beacon/BeaconManager.java, src/main/java/org/altbeacon/beacon/service/MonitorState.java
Hello, I requested the feature that allows to change the exit region time. So, I made the straightforward solution via static variable and methods of BeaconManager where all settings are located.
=> make the region exit time configurable

build.gradle, src/main/java/org/altbeacon/beacon/BeaconManager.java
BeaconManager used to either return a regular ArrayList or unmodifiableList depending on whether any consumers were bound to the BeaconManager. This unnecessarily caused ConcurrentModificationExceptions if used incorrectly, and was easily bypassed. Replace with the simpler CopyOnWriteArrayList.
I ran the unit tests and did some local testing on a snapshot build and it seemed to be ok.
=> Use CopyOnWriteArrayList for beacon parser list

build.gradle, src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScannerForLollipop.java
* Upgrade to SDK 23 (Marshmallow)
* When scanning in the background, do an unfiltered scan on each main scan cycle in case chips do not support filtering, or no more filter slots are unavailable.  This will cause background detections on Android 5.x+ to still happen in 5 minutes even if there are no hardware acceleration capability.
=> Android 6.0 Changes

src/main/AndroidManifest.xml, src/main/java/org/altbeacon/beacon/BeaconParser.java, src/main/java/org/altbeacon/beacon/Region.java, src/test/java/org/altbeacon/beacon/GattBeaconTest.java, src/test/java/org/altbeacon/beacon/RegionTest.java
This addresses a bug where Eddystone beacons with 1 or 2 identifiers didn't match region with three null identifiers.  It is important that these do match, as most examples show setting up a region to match all beacons that has three null identifiers.
This bug was introduced in commit 341be144 and first appeared in release 2.6
This addresses #294
=> Fix region matching with fewer ids

src/main/AndroidManifest.xml
The `ACCESS_COARSE_LOCATION` permission is not necessary on pre-M devices and therefore should only be requested on M.
=> Only request ACCESS_COARSE_LOCATION permission on M

README.md
In Markdown, for each layer of lists, an additional four spaces need to be added so that code blocks will appear.
=> Add proper indentation for code snippet.

src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScanner.java
As it is stated in the comment when cancelling wakeup alarm it was intended to be defered to the long long future due to some Samsung devices constraints. Actually, the time to deploy alarm parameter was passed with overflow (Long.MAX_VALUE + currentTime() is actually in the past) and the alarm is deployed right after it's creation. Not as it is intended to be. This commit fixes it.
=> Fix cancelling wakeup alarm

src/main/java/org/altbeacon/beacon/BeaconManager.java, src/main/java/org/altbeacon/beacon/service/BeaconService.java, src/main/java/org/altbeacon/beacon/service/scanner/NonBeaconLeScanCallback.java
The AltBeacon library is beautiful (sucking up here a little bit), and fixes a lot of general non-Beacon BLE scanning issues.
If a single app wants to scan both Beacon and non-Beacon BLE devices, then it currently has to spin up two active scanners: 1) AltBeacon library for Beacons, 2) a second android.bluetooth.le.BluetoothLeScanner to scan for non-BLE devices that duplicates all of the AltBeacon's non-Beacon agnostic BLE scanning logic.
This would be both hard to maintain and inefficient use of CPU.
I propose that AltBeason expose a callback that allows processing of non-Beacon BLE devices.
My proposed change is pretty simple and does not harm existing behavior.
An implementation only needs to call "BeaconManager.getInstanceForApplication(...).setNonBeaconScannedCallbacks(...)" to opt …
=> Add callback allowing processing of scanned non-Beacon BLE devices

src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScannerForLollipop.java, src/main/java/org/altbeacon/beacon/service/scanner/ScanFilterUtils.java, src/test/java/org/altbeacon/beacon/service/scanner/ScanFilterUtilsTest.java
This adds the use of hardware scan filters for service advertisements like Eddystone when a scanning app is in background mode.  This will make detections happen within a few seconds instead of within five minutes at default settings.
=> Fast background detection for Eddystone

src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScanner.java
This fixes a race condition where stopping monitoring and scanning and then immediately restarting monitoring and scanning leaves the library in a state where it is not doing any scanning at all.  This was caused by a race condition that kept the `mScanCyclerStarted` flag from being set to false if a scan cycle was not allowed to end normally after stopping scanning/monitoring before restarting again.
This change eliminates that race condition by setting the flag immediately.
=> Stopping and starting monitoring disables scans

src/main/java/org/altbeacon/beacon/BeaconParser.java, src/test/java/org/altbeacon/beacon/BeaconParserTest.java
When comparing two byte arrays, check first to see if one is shorter than the other.  If so, consider them unequal and short-circuit the comparison rather than crash on an ArrayIndexOutOfBoundsException looping through the bytes.  Fixes #323
=> Fix crash on comparison overrun 

src/main/java/org/altbeacon/beacon/AltBeaconParser.java, src/main/java/org/altbeacon/beacon/Beacon.java, src/main/java/org/altbeacon/beacon/BeaconParser.java, src/test/java/org/altbeacon/beacon/BeaconParserTest.java
This adds a new identifier field to a `BeaconParser`, which can be used in the constructor like this:  `new BeaconParser("my_beacon_type")`
A corresponding `parserIdentifier` field has been added to `Beacon` which allows access to this field for any beacon constructed from this parser:  `beacon.getParserIdentifier(); // Returns "my_beacon_type"`
This is useful for scanning for multiple beacon types and then easily knowing which type each ranged beacon is.
=> Track parser identifier in both BeaconParser and Beacon

src/main/java/org/altbeacon/beacon/BeaconParser.java, src/main/java/org/altbeacon/beacon/utils/EddystoneTelemetryAccessor.java, src/test/java/org/altbeacon/beacon/BeaconParserTest.java, src/test/java/org/altbeacon/beacon/utils/EddystoneTelemetryAccessorTest.java
This experimental utility allows recreating the raw bytes of an Eddystone-TLM advertisement.  This is useful, because Google APIs allow reporting of detected telemetry packets to their backend, but want the raw bytes to be sent to the server.  While this library is designed to decode beacon packets into fields based on their layout, and format beacon fields into packets for advertising purposes, it does not easily allow access to raw bytes of a previously detected beacon.  This utility makes that possible.
To use this feature, you will need a copy of the library with this code added.  An ad-hoc release is available for download [here.](https://github.com/AltBeacon/android-beacon-library/releases/tag/ad-hoc-eddystone-telemetry-accessor)
Once your project is compiled with a library version …
=> Add utility to access raw Eddystone-TLM bytes

src/main/java/org/altbeacon/beacon/service/DetectionTracker.java, src/main/java/org/altbeacon/beacon/service/MonitorState.java, src/main/java/org/altbeacon/beacon/service/RangedBeacon.java, src/main/java/org/altbeacon/beacon/service/RunningAverageRssiFilter.java, src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScanner.java, src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScannerForJellyBeanMr2.java, src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScannerForLollipop.java, src/main/java/org/altbeacon/bluetooth/BluetoothCrashResolver.java
See issue #335
I branched this off the 2.7.1 tag as the current master does not detect beacons on my device.
Besides using `ELAPSED_REALTIME_WAKEUP` alarms, use `SystemClock.elapsedRealTime()`  whenever checking periodic intervals, to be resilient against clock shifts.
=> Use realtime clock for scanning intervals and timers

src/main/java/org/altbeacon/beacon/BeaconManager.java
This commit fixes the issue with multiple beacon service consumers binding.
Till now only one cunsumer could be bound due to the fact that only one ServiceConnection existed.
Trying to bind another consumer resulted with no onBeaconServiceConnected() callback as Android does not produce antoher onServiceConnected() callback when same ServiceConnection is used multiple times.
=> Beacon service multiple bind

src/main/java/org/altbeacon/beacon/powersave/BackgroundPowerSaver.java
A more logical way to use the BackgroundPowerSaver would be to register it yourself.
Assuming `app` is an instance of Application, you can do
`app.registerActivityLifecycleCallbacks(new BackgroundPowerSaver(context));`
As this class is right now, you can already do this.
However, this would mean you register the object twice, which might cause some implications.
I haven't tested what it might do, but registering it twice can't be good.
Also, I'm unsure why you required API 18 for this class, since `Application.registerActivityLifecycleCallbacks` is available since API 14.
This would also make it possible to pass any `Context` in the constructor and still be able to use it.
This is a non-obvious breaking change, since no errors will be thrown if a user updates the library and this change …
=> Adjust the BackgroundPowerSaver so it accepts any context

src/main/java/org/altbeacon/beacon/BeaconParser.java, src/test/java/org/altbeacon/beacon/GattBeaconTest.java
This simply adds a pre-defined layout for parsing the pre-Eddystone UriBeacon format, which is similar to Eddystone-URL format.  Also adds a unit tests that demonstrates it can be parsed successfully.
=> Add support for pre-Eddystone UriBeacon layout

src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScanner.java
This fixes a bug reported in  #363 where scanning would not start on Android 4.x devices if they did not have the ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION in the AndroidManifest.xml.  The library's AndroidManifest.xml only conditionally includes ACCESS_COARSE_PERMISSION if on SDK 23+.
=> Don't check for location permission on SDK < 23 before scan start 

src/main/java/org/altbeacon/beacon/service/MonitoringStatus.java
Replaced `$` for `%` to display the correct arguments in the log
=> Missing log arguments due to typo error

src/main/java/org/altbeacon/beacon/BeaconParser.java, src/test/java/org/altbeacon/beacon/BeaconParserTest.java
Bug in BeaconParser:
- Unable to parse Long data correctly when the size of data is longer than 4 bytes. 
Cause: Incorrect usage of `Long.parseLong` on hexadecimal formatted string
Add test case
- BeaconParserTest.testCanParseLongDataTypeOfDifferentSize()
It tests whether data fields with various sizes can be correctly parsed or not. 
Related to #173
=> Fix BeaconParser bug: Unable to parse Long data type correctly

src/main/java/org/altbeacon/beacon/BeaconManager.java
#143 Fix potential memory leak when passing an `Activity` to `BeaconManager.getInstanceForApplication(Context context)` , because the `BeaconManager` would keep a reference to that `Context`.
The fix ensures that `BeaconManager` always keeps a reference to the application `Context`.
=> Fix 143 potential context leak

build.gradle, src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScanner.java, src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScannerForLollipop.java
This change limit restarting scans on Android N to once every 6 seconds to comply with the OS-imposed limit of 5 BLE scans every 30 seconds per app.  Without this change, scans at default rates are blocked for 24.5 out of every 30 seconds causing spurious exits and entry events.
Addresses #418
=> Avoid spurious entry/exit events on Android N

src/main/java/org/altbeacon/beacon/service/MonitoringStatus.java
After a MonitoringStatus restore, beacons that were inside, have their initial lastSeenTime and may trigger quickly as exit - enter. Mark all that are inside again.
=> MonitoringState preservation improvement

build.gradle, proguard-rules.pro
By providing the proguard rules, apps that use AltBeacon no longer have to include the proguard rules themselves.
=> Provide proguard rules for library users.

src/main/java/org/altbeacon/beacon/service/BeaconService.java, src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScanner.java, src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScannerForJellyBeanMr2.java, src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScannerForLollipop.java
This pull request fixes the problems reported in issue #136 where ANRs are caused by AltBeacon accessing the BluetoothAdapter (which has heavy internal synchronization and even explicit wait() calls) from the main thread.
A HandlerThread is used for the purpose, and no internal state is accessed from within the posted runnables so that it's not necessary to make the CycledLeScanner classes thread safe. In the same way, callbacks from the BluetoothAdapter are already always executed from the main thread (they're called, internally, from a Handler created with the main looper).
=> Start and stop BLE scans from a background thread to prevent blocking the UI (issue #136)

src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScanner.java, src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScannerForLollipop.java
This is an attempt to fix crash reports from #440 #429 which appear to be caused by unexpected SecurityExceptions thrown at runtime when trying to access Bluetooth services, despite the fact that permissions have been granted to the app.  
This solution simply catches those unexpected SecurityExceptions to prevent the app from crashing when trying to scan for beacons. 
Some reports suggest this is happening due to apps running inside a Samsung Knox container, which allows denying access to services like Bluetooth to specific applications, despite access being available on the Android device in general.
Does anybody have access to a Samsung Knox device who could test this solution?  If so please comment on this PR.
This is a new solution to replace an earlier proposal in #428.
=> Protect against SecurityException crashes caused by Samsung Knox

src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScannerForLollipop.java
This is an attempt to prevent crashes on HTC devices per #414 by refusing to start/stop scans if bluetooth is off.
This needs to be tested on an HTC device with 6.0+ to verify it works
=> Don't start or stop scans if bluetooth state is off 

CHANGELOG.md
This adds a changelog file to the project root. This is a common file
many open source projects include. This provides a standard place for a
developer to look to get a quick summary of changes; say before an
upgrade.
Additionally, this type of file is GitHub agnostic. So if the project is
ever moved the change summary history is preserved. This also allows an
offline developer to see the summary while working on the project.
This changelog is formatted with markdown to provide a nice display in
the web UI. It also includes the pull request numbers for each of the
entries. This is great because it easily allows someone to look up the
associated code changes and any accompanying discussions.
Lastly, this includes the developer's name who did the work. Easily
accessible public credit is …
=> Add changelog to project root

build.gradle
This allows us to start annotating fields, methods, and parameters with
helpful annotations such as `@NonNull` and `@MainThread`. Several newer
Android APIs have already started using these annotations. Using these
types of annotations helps identify potential bugs early in the
development cycle through code inspections and lint (Android Studio is
configured by default to highlight such issues inline).
While this is a `compile` dependency it should be backwards compatible
with older IDEs. This is accomplished for generated AAR and tar archives
by including the annotations in a separate file within the archive;
non-supporting IDEs will simply ignore the file.
See Also:
- https://developer.android.com/studio/write/annotations.html
- …
=> Include support annotations

src/main/java/org/altbeacon/beacon/service/Callback.java
This catches a possible crash caused by a `DeadObjectException` which can potentially occur when processing scan data.
This comes from some old crash reports that were related to an older ABL release. This had been patched in a separate local branch to mitigate the issue. After applying it we stopped receiving the 2nd hand reports of the crashes. Unfortunately, we never received details on which devices or OS builds the original crash was happening on.
Either way this seems like a safe patch to apply without side effects.
<details>
<summary>Original Crash Stack Trace</summary>
```
Fatal Exception: java.lang.RuntimeException: Failure from system
at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1365)
at android.app.ContextImpl.startService(ContextImpl.java:1306)
at …
```
=> Try to prevent crash due to `DeadObjectException`

CHANGELOG.md, src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScanner.java
Using the prior scan end time to calculate when we can stop the current scan cycle causes an immediate scan stop under two conditions:
- this is the first scan cycle
- scanning has been stopped for longer than 6 seconds (a more generalized case of the first scan cycle)
The simple solution is to always check the scan start time. It will always be true, since only one scan can happen at a time, that the previous stop value is less than the start value. Thus the start value plus the minimum Android N scan time will always be greater than the last stop time equivalent. This guarantees that with normal continuous scan cycling there will be no more than five scans.
=> Fix intermittent scans

src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScanner.java
In `CycledLeScanner` the bluetooth adapter is only ever set to a non-`null` value. Additionally, the call to `scanLeDevice(false)` runs it's sad path branch regardless of if the bluetooth adapter has been set. This branch includes a call to `stopScan()` and also sets the `mLastScanCycleEndTime` time.
This means that when the cycler has been running the first call to `stop()` will call `scanLeDevice(false)` from the positive branch of the `mScanCyclerStarted` check. This will stop the scan and set the time field. Then, since the bluetooth adapter will never be `null`, a second call to `stopScan()` will occur resulting in unnecessary work; work that will happen in a already stopped state - which may be unexpected.
After this, any subsequent calls to `stop()` will incorrectly reset the …
=> Eliminate extra scan stop call

src/main/java/org/altbeacon/beacon/powersave/BackgroundPowerSaver.java
This is an attempt to fix crashes in the BackgroundPowerSaver reported in #469 caused by a null BeaconManager.  This change moves the construction of the BeaconManager before the registration of activity lifecycle callbacks, so if an exception is thrown creating the BeaconManager, it will not be left in a null state.
It is unclear whether this will solve the problem, so this small change is being put in a test build.
=> Fix power saver crash

src/main/java/org/altbeacon/beacon/BeaconManager.java
If BLE is unsupported on a device, there is no point in starting the scanning service.  The library has long refused to start the scanning service if on a pre-Android 18 device (which does not support BLE APIs).  So the effects of not starting the scanning service at startup under this similar condition are well known and already in the wild.
This may prevent a stackoverflow crash reported in  #472, which was believed to happen on a device with Android 4.3+ but no BLE support.
=> Don't start scanning service if BLE unsupported

CHANGELOG.md, src/main/java/org/altbeacon/beacon/service/BeaconService.java, src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScanner.java, src/main/java/org/altbeacon/beacon/service/scanner/DistinctPacketDetector.java, src/test/java/org/altbeacon/beacon/service/scanner/DistinctPacketDetectorTest.java
**Background:** 
Restarting scanning (stopping and immediately restarting) is necessary on many older Android devices like the Nexus 4 and Moto G because once they detect a distinct BLE packet in a scan, subsequent detections do not get a scan callback.  Stopping scanning and restarting clears this out, allowing subsequent detection of identical advertisements.
On most newer devices, however, this is not necessary, and multiple callbacks are given for identical packets detected in a single scan.   Because the library has no simple way of knowing whether the device can detect duplicate advertisements per scan, scanning is restarted regardless.
**Change**
This adds a detection of duplicate identical advertisements in a single scan.   If duplicates are ever detected, scans are no longer …
=> Don't restart scanning if device detects duplicate advertisements per scan 

src/main/java/org/altbeacon/beacon/BeaconManager.java
`
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.util.ArraySet.size()' on a null object reference
at android.content.Intent.writeToParcel(Intent.java:8765)
at android.content.pm.IPackageManager$Stub$Proxy.queryIntentServices(IPackageManager.java:3422)
at android.app.ApplicationPackageManager.queryIntentServicesAsUser(ApplicationPackageManager.java:966)
at android.app.ApplicationPackageManager.queryIntentServices(ApplicationPackageManager.java:980)
at org.altbeacon.beacon.BeaconManager.verifyServiceDeclaration(BeaconManager.java:917)
at org.altbeacon.beacon.BeaconManager.(BeaconManager.java:252)
at org.altbeacon.beacon.BeaconManager.getInstanceForApplication(BeaconManager.java:244)
at org.altbeacon.beacon.startup.StartupBroadcastReceiver.onReceive(S …
=> fix nullpointer bug

CHANGELOG.md, src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScanner.java, src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScannerForLollipop.java
This fixes a failure to stop BLE scanning in two scenarios caused by #491:
1. When there is a nonzero between scan period.
2. When the unbind() is called on the BeaconManager to stop the BeaconService.
This was reported here:  http://stackoverflow.com/questions/43835705/how-to-properly-stop-scanning-beacon-using-android-beacon-library-altbeacon/43836157#43836157
Testing on Nexus 5X, showing logs after a call to
`BeaconReferenceApplication.this.unbindService(connection);`
Without change (note beacon packets are detected after service stops):
```
05-10 10:55:42.262 31353-31353/org.altbeacon.beaconreference E/BeaconService: onDestroy()
05-10 10:55:42.263 31353-31353/org.altbeacon.beaconreference D/BluetoothCrashResolver: stopped listening for BluetoothAdapter events
05-10 10:55:42.264 …
```
=> Fix failure to stop scans

src/main/java/org/altbeacon/beacon/service/BeaconService.java, src/main/java/org/altbeacon/beacon/service/scanner/DistinctPacketDetector.java
No functionality change here. This simply cleans up some unused statements, spelling, and adds in nullability annotations. The nullability annotations help Android Studio better catch potential development time errors based on object presence assumptions.
This includes a simple comment addition about the thread safety of the classes. These classes are only used in one location currently. It's easier to manage thread safety as necessary in the encapsulating class. So this simply documents that this class isn't thread safe (i.e.  it's up to the client to ensure thread safety as necessary).
=> Minor updates

src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScannerForLollipop.java
On occasion I noticed a "Scan Failed" in the logs. This improves the logged error message to report the associated reason based on the error code. If it's an error we don't know about it includes the error code in the message for further research.
=> Log more specific error message on scan failure

CHANGELOG.md, build.gradle, src/androidTest/java/org/altbeacon/beacon/NotifierSetCopyBenchmarksTest.java, src/main/java/org/altbeacon/beacon/BeaconManager.java, src/main/java/org/altbeacon/beacon/distance/ModelSpecificDistanceCalculator.java, src/main/java/org/altbeacon/beacon/powersave/BackgroundPowerSaver.java, src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScannerForLollipop.java
This is mostly just a nullability annotation update with a few minor code changes. However, there were two sets of significant changes which actually fixed a few potential bugs:
- Fix possible `NullPointerException` with `BackgroundPowerSaver` on devices prior to Android 4.3 Jelly Bean MR 2 (API 18)
This eliminates the short circuit in the guard clause which would prevent a `BeaconManager` from being set. The basic creation of a `BeaconManager` instance doesn't require Android 18; running that instance will and is turned into a no-op at that point. While here nullability annotations were included and the `BeaconManager` instance was made `final` (this is how the NPE was caught).
- Fix rare edge case causing `NoSuchElementException` when using the legacy …
=> Misc minor fixes

src/main/java/org/altbeacon/beacon/service/BeaconService.java, src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScanCallback.java, src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScanner.java, src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScannerForJellyBeanMr2.java, src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScannerForLollipop.java, src/main/java/org/altbeacon/beacon/service/scanner/NonBeaconLeScanCallback.java
This is a follow up to #507 
- Fix where scanner thread is quit
This fixes what I believe was a simply copy-paste error regarding how the scanner thread is quit. This uses the scanner thread handler, instead of the main thread handler, to schedule the `quit` operation. This way any queued scan jobs (such as a stop) complete before we quit the thread. This is what the comment states, but wasn't what the code implemented.
Fix scan stop when bound but no monitored / ranged regions.
This adds a guard to ensure that we only attempt any further scans when the scan cycler is started. This helps ensure the cycler has terminated scanning for the case where all regions have been removed but the service is still bound. In this case only `stop` will be called (instead of both `stop` and `destroy`). …
=> Scan documentation update and stop scan bug fix

CHANGELOG.md, src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScanner.java
This is a fix for #518 which reports that scanning gets stuck in an off state under certain conditions when bluetooth has been turned off and turned back on.
The problem exists in 2.10 but not 2.9.It is caused by the fact that we generally leave scanning on all the time as of 2.10, and if bluetooth is turned off, we need to know to restart scanning when bluetooth is back on.  This was not an issue in 2.9 and earlier because we always stopped and restarted scanning every second or so in the foreground.
The following tests show that the problem exists in 2.10 and master, but not after the change in this branch.
```
==== 2.10 =====
$ adb logcat  | grep -e "beacon detected"  -e "bluetooth is off" -e "Bluetooth is disabled"  -e "starting non-filtered scan"
05-30 23:47:51.694  6709  6709 D …
```
=> Restart scanning after bluetooth is off

CHANGELOG.md, build.gradle, src/main/java/org/altbeacon/beacon/service/RangedBeacon.java, src/main/java/org/altbeacon/beacon/service/RunningAverageRssiFilter.java, src/test/java/org/altbeacon/beacon/service/RunningAverageRssiFilterTest.java
The ability to configure this setting was broken as reported in https://github.com/AltBeacon/android-beacon-library-reference/issues/30.  This change makes the API work as intended so the documentation is correct.
=> Fix `RunningAverageRssiFilter.setSampleExpirationMilliseconds`

CHANGELOG.md, src/main/java/org/altbeacon/beacon/service/BeaconService.java, src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScanner.java
Android N introduced a restriction that any Bluetooth LE scan running for over 30 minutes would be converted to an "opportunistic" scan, effectively meaning it is disabled unless some other app is scanning.  This is intended to save battery, but affects beacon scanning in this library as described in #526.
While this makes sense in general, there are some cases where it is reasonable to override this behavior.  Examples include a wall-powered Android Things  device meant to be a full-time beacon scanner, or a phone app that ranges in the foreground for the case where the user leaves the app up and running for > 30 minutes.
This change circumvents this restriction by stopping scanning at the last opportunity before the 30 minute period is hit, and letting scanning restart on the next scan …
=> Allow forcing long scans on Android N

CHANGELOG.md, src/main/AndroidManifest.xml
This addresses new Google Play submission errors reported in #520 and #521 when using the library based on a reported conflict between two permission tags.
This changes the library manifest to use 
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
rather than 
<uses-permission-sdk23 android:name="android.permission.ACCESS_COARSE_LOCATION"/>
This effectively reverts the change in #296.  The disadvantage is that the permission will now be shown to users at install time on Android 5.x and earlier, even though it is not needed.  But this is a small disadvantage relative to not being able to submit to the Play Store.
If it is important not to request this permission to users on Android 5.x and earlier, then it is possible to not do so by putting this in your app's …
=> Fix Google Play manifest validation errors

src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScannerForLollipop.java
This is the result of several refactor steps which set out to improve the clarity between the relation ship of the flags `mScanDeferredBefore`, `mMainScanCycleActive`, and the `deferScanIfNeeded` method. This ultimately results in the removal of the `mScanDeferredBefore` flag.
Refactor Steps
--------------
1. Extract defer check into boolean flag
```diff
@@ -79,7 +79,8 @@ public class CycledLeScannerForLollipop extends CycledLeScanner {
protected boolean deferScanIfNeeded() {
// This method is called to see if it is time to start a scan
long millisecondsUntilStart = mNextScanCycleStartTime - SystemClock.elapsedRealtime();
-        if (millisecondsUntilStart > 0) {
+        final boolean deferScan = millisecondsUntilStart > 0;
+        if (deferScan) {
mMainScanCycleActive = false;
long …
```
=> Refactor away `mScanDeferredBefore` flag

CHANGELOG.md, src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScannerForLollipop.java
This fixes "Scanning too frequently" error with non-zero betweenScanPeriod and scanPeriod+betweenScanPeriod < 6000, and full-power scanning  staying on for foreground scans with a non-zero betweenScanPeriod.
See here for more details about the problem:  https://github.com/AltBeacon/android-beacon-library/issues/554#issuecomment-321019248
=> Fix bugs with  nonzero foreground betweenScanPeriod

CHANGELOG.md, src/main/java/org/altbeacon/beacon/BeaconManager.java, src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScanner.java
This resolves a case of scans being left on (forever) after unbind is called on the BeaconManager as reported in #567.
The problem was that scanning may not be stopped at the end of a scan cycle (for the case of avoiding too many scans per minute on Android 7+, or for keeping scans going because multiple packet detections are available.)  This addresses that by setting a flag if scanning is left on for one of these cases and then explicitly stopping it at the end of the cycle.
A test run that shows this in operation is shown in the log sequence below.  The fix is triggered on the line that says "Stopping scanning previously left on".
This test run used the reference app with this modification in the application class:
```
Log.d(TAG, "Starting scanning for 20 seconds"); …
```
=> Prevent scanning being left on after unbind

CHANGELOG.md, src/main/java/org/altbeacon/beacon/service/ScanState.java
Fixes #568 showing an ugly stack trace during normal operations on first run of an app when the serialization file does not exist yet.
=> Suppress file not found on scan state deserialize

CHANGELOG.md, src/main/java/org/altbeacon/beacon/service/ScanJob.java
When upgrading an existing app to 2.12 the ScanState serialization file would not yet exist.  Then when the app ran for the first time, it would find a missing file when deserializing it, yielding a scan period of 0.  This would then cause a stackoverflow constantly stopping and starting scans.  This was reported in #571.
The fix is to check if the scan period is zero and if so, immediately quit the scan job.  A test showing the fix works is in the log below.
```
$ adb logcat | grep ScanJob
08-27 16:07:42.219  1125  1125 I ActivityManager: Start proc 15083:org.altbeacon.beaconreference/u0a236 for service org.altbeacon.beaconreference/org.altbeacon.beacon.service.ScanJob
08-27 16:07:42.631 15083 15083 I ScanJob : Running periodic scan job: instance is …
```
=> Fix stack overflow caused by scanPeriod of 0s

CHANGELOG.md, src/main/java/org/altbeacon/beacon/service/MonitoringStatus.java, src/main/java/org/altbeacon/beacon/service/ScanHelper.java, src/test/java/org/altbeacon/beacon/service/MonitoringStatusTest.java
Apps that dynamically change regions frequently are apt to get a ConcurrentModificationException when ScanJobs serialize these monitored regions.   This change fixes that by storing the regions in a ConcurrentHashMap.
=> Fix ConcurrentModificationException on RegionState

CHANGELOG.md, src/main/java/org/altbeacon/beacon/distance/ModelSpecificDistanceCalculator.java, src/main/java/org/altbeacon/beacon/service/MonitoringStatus.java, src/main/java/org/altbeacon/beacon/service/ScanHelper.java, src/test/java/org/altbeacon/beacon/service/MonitoringStatusTest.java
Simple fix to address the ConcurrentModificationException long reported in #56, and once thought fixed.  This change avoids another case by writing the class' instance of modell map in an atomic way.
=> Fix CME in ModelSpecificDistanceCalculator

CHANGELOG.md, src/main/java/org/altbeacon/beacon/service/ScanJob.java
As described in #577, in some cases a ConcurrentModificationException will cause an app using the library to crash if it modifies the monitored regions at the same time the app begins a passive scan.  This change fixes that.
=> Fix ConcurrentModificationException starting passive scan on Android 8

src/main/java/org/altbeacon/beacon/service/ScanJob.java, src/main/java/org/altbeacon/beacon/service/ScanJobScheduler.java
When the library is in foreground mode, and the job expires, immediately schedule the next job.  This should give virtually constant scanning when in the foreground, matching behavior of using the BeaconService before Android O.
Ref: https://github.com/AltBeacon/android-beacon-library/issues/605
Tested on Nexus 5X with Android 7/8
Also passed unit tests in gradle build.
=> Continuous Scanning While in Foreground on Android 8

CHANGELOG.md, src/main/java/org/altbeacon/beacon/service/RangedBeacon.java, src/test/java/org/altbeacon/beacon/service/RunningAverageRssiFilterTest.java
This fixes #627 which is a regression of AltBeacon/android-beacon-library#523 (AltBeacon/android-beacon-library-reference#30). It was introduced in commit f084042efa3264ba (PR AltBeacon/android-beacon-library#484) where the `RunningAverageRssiFilter` has it's value constantly reset after every cycle in [`RangedBeacon#commitMeasurements`](https://github.com/AltBeacon/android-beacon-library/commit/f084042efa3264ba673814eec88ce591f1ac66df#diff-65311818bc092d4192549ca6a7932a8aR50).
=> Preserve RSSI expiration  on ranged beacon commit

CHANGELOG.md, src/main/java/org/altbeacon/beacon/AltBeacon.java, src/main/java/org/altbeacon/beacon/Beacon.java, src/test/java/org/altbeacon/beacon/AltBeaconTest.java, src/test/java/org/altbeacon/beacon/BeaconTest.java, src/test/java/org/altbeacon/beacon/service/RangingDataTest.java
This is a follow up to #629 where it was noticed that some of the internal `Beacon` data fields were not being copied through parceling / constructors as expected.
=> Improve `Beacon` data copy

CHANGELOG.md, src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScannerForLollipop.java, src/main/java/org/altbeacon/beacon/service/scanner/ScanFilterUtils.java
Android 8.1 now blocks scans with the screen off unless there is an associated ScanFilter.  This change adds an empty ScanFilter that matches anything so that results are still returned on Android 8.1 in these conditions.  This addresses #633
I have not tested this on an Android 8.1 device yet as I do not have one handy.  I have only verified that the scans still work with this wildcard filter added on a pre-8.1 device.
=> Allow scans with screen off on Android 8.1

CHANGELOG.md, src/main/AndroidManifest.xml, src/main/java/org/altbeacon/beacon/service/ScanJob.java, src/main/java/org/altbeacon/beacon/service/ScanJobScheduler.java
The Job Scheduler ScanJobs used in Android 8 has a hard-coded job id of 1 and 2.  Because this job id must be unique per application, this can cause collisions with other app job ids.  This changes the default job ids to be a high integer number, and declares them in AndroidManifest.xml:
```
<service android:name=".service.ScanJob"
android:permission="android.permission.BIND_JOB_SERVICE" >
<meta-data android:name="immmediateScanJobId" android:value="208352939" />
<meta-data android:name="periodicScanJobId" android:value="208352940" />
</service>
```
These may be overridden in the app manifest as needed like this: 
```
<service android:name="org.altbeacon.beacon.service.ScanJob">
<meta-data android:name="immediateScanJobId" android:value="1000" tools:replace="android:value"/>
<meta-data …
```
=> Configurable scan job ids

CHANGELOG.md, build.gradle, src/main/AndroidManifest.xml, src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScannerForLollipop.java, src/main/java/org/altbeacon/bluetooth/BluetoothMedic.java, src/main/java/org/altbeacon/bluetooth/BluetoothTestJob.java
This adds an optional Bluetooth Medic class that can be used to look for crashes in the Bluetooth stack, and optionally power cycle bluetooth to attempt to recover when crashes are found.   This has been proven to be effective in testing with the the Samsung J3 and the Huawei P9 Lite.
The medic performs two optionally configurable tests, one that does a brief bluetooth scan and one that transmits over bluetooth.   Both can detect a bluetooth stack crash based on the error codes returned if there are failures.
The Medic can be run in three modes: passive manual and automatic.  Automatic mode uses a Scheduled Job to run the configured tests every 15 minutes.  Manual mode allows the user to run the tests manually at a time of their choosing.   Passive mode simply looks for failures on the …
=> Add Bluetooth Medic

src/main/java/org/altbeacon/beacon/BeaconManager.java
This addresses the issue reported in #613 where isBound and isAnyConsumerBound don't work with schedule jobs (Android 8+ default).  This also reportedly caused trouble in #641.
This is a proposed replacement for pull request #600
@hashbrown  and @carlonzo, both of you proposed fixes for this problem, so any comments are welcome.
=> Fix flawed logic on BeaconManager#isBound

CHANGELOG.md, src/main/java/org/altbeacon/beacon/BeaconTransmitter.java, src/test/java/org/altbeacon/beacon/service/MonitoringStatusTest.java
Being able to set a beacon advertisement as "connectable" causes 3
additional bytes to be prepended to the advertisement PDU.
The value of these 3 bytes are: `0x02011a`.
They are:
1. PDU length (02)
2. PDU type (01)
3. Payload (1a)
These 3 bytes are present in an iBeacon advertisement on iOS. However,
they do not appear in the equivalent advertisement on Android using
`BeaconTransmitter` without setting the `AdvertiseSettings` to
"connectable."
Ref #141.
=> Adds connectable property to BeaconTransmitter

CHANGELOG.md, src/main/java/org/altbeacon/beacon/BeaconManager.java
This addresses the issue reported in #671, where a developer was surprised that ranging callbacks did not come in when the backgroundBetweenScanPeriod was set to a short interval on Android 8+.  This change adds a warning in the logs saying that setting such a short scan period will not work.
This is not a fix, but will hopefully increase the visibility of this Android 8 limitation to users of the library.
=> Add warning about setting short scan periods on Android 8

CHANGELOG.md, src/main/java/org/altbeacon/bluetooth/BluetoothMedic.java
This is an attempt to resolve crashes on the BluetoothMedic reported with in #668 and #672 
Since these crashes were only reported remotely from field devices, steps to reproduce have not been confirmed and solutions are based only on theory -- they have not been verified to fix anything.
=> Fix runtime crashes reported from the field.

CHANGELOG.md, src/main/java/org/altbeacon/beacon/BeaconManager.java
This is a documentation and LogCat warning change to address the concern in  #673 that calling `setEnableScheduledScanJobs(false)` can break functionality on Android 8+
=> add warning about disabling scan jobs on Android 8+

CHANGELOG.md, src/main/java/org/altbeacon/beacon/BeaconParser.java, src/test/java/org/altbeacon/beacon/GattBeaconTest.java
This crash was reported in the field via @mharper  when a malformed Eddystone-URL packet was detected with a packet so short that the URL length would effectively be negative.  Because the library allows variable length Eddystone-URL identifiers, it did not have protections on a minimum length.
The fix is to enforce that the length must at least be 1, and to fail parsing the packet if it is not.
`06-13 07:50:53.081 788 829 E ScanHelper: Exception while parsing scan data 0201060303aafe0416aafe100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 from device null with parser s:0-1=feaa,m:2-2=10,p:3-3:-41,i:4-20v`
@mharper, this look good to you?
=> Fix crash parsing malformed Eddystone-URL packet 

CHANGELOG.md, src/main/java/org/altbeacon/beacon/BeaconManager.java, src/main/java/org/altbeacon/beacon/service/ScanJobScheduler.java
Before this change, calling BeaconManager.unbind(...) would never stop scheduled scanning jobs if they were in use.  This fixes that so after the last consumer is unbound, all scheduled scan jobs will be cancelled.
Fixes #657
=> Cancel schedule jobs after last consumer unbound

CHANGELOG.md, src/main/java/org/altbeacon/beacon/service/ScanHelper.java
This is an attempt to fix #701.   I have not tested that this works, as there are no known ways to reproduce the problem.  It has only been seen in crash logs.
=> Catch of exception thrown by Android stopping scan

CHANGELOG.md, src/main/java/org/altbeacon/beacon/service/RangeState.java
This NPE probably happens in a race condition where the RangedBeacon is removed by another thread in the middle of the two step process to (1) check if the RangedBeacon is in the collection and (2) pull the RangedBeacon from the collection, causing a NPE in step 2.
This change fixes that problem by making it a one step process.
=> Fix NPE on RangedBeacon per #638

CHANGELOG.md, src/main/java/org/altbeacon/beacon/service/BeaconService.java
These were caused by multiple NotificationProcessor registrations when binding and unbinding as described in #735
=> Fix duplicate raging/monitoring callbacks

src/main/java/org/altbeacon/beacon/service/ScanJobScheduler.java
This caused multiple `NotificationProcessor` registrations when binding and unbinding.
This PR and #745 will completely fix #735
=> Fix leaked NotificationProcessor in ScanJobsScheduler

CHANGELOG.md, src/main/java/org/altbeacon/beacon/service/ScanHelper.java, src/main/java/org/altbeacon/beacon/service/ScanJob.java
The root cause of the crash is the inability to start a new thread needed to scan for beacons when an Intent-based scan returns results and launches the app in the background via a ScanJob.  This was reported in #589.
The fix is to simply catch the OutOfMemory error in two places where the thread is started, and log the error condition.  This will let the app try again on the next opportunity (probably the next ScanJob run 15 minutes later) to start a scan.
It's still unclear why this happens at all.  This should not be necessary.
=> Prevent OutOfMemoryError Crash on Android 8

src/main/java/org/altbeacon/beacon/service/ScanHelper.java
Sometimes the BluetoothLeScanner is null. This only adds a null check before start the scanning.
=> Fix #780: NullPointerException on startScan()

CHANGELOG.md, src/main/java/org/altbeacon/beacon/service/BeaconService.java
As reported in #760, some devices with Android 5.x will get stuck in crash recovery.  The BluetoothCrashResolver is only designed to help a problem known to be in 4.3.x and 4.4.x so there is no point in leaving it enabled on 5.x or higher.    This change disables it.
=> disable BluetoothCrashResolver if Android version is 5.0 or higher

CHANGELOG.md, build.gradle, src/main/java/org/altbeacon/beacon/BeaconManager.java, src/main/java/org/altbeacon/beacon/service/ScanJobScheduler.java
This fixes a case where callbacks were not delivered after calling unbind/bind on the BeaconManager when using ScanJobs.
=> Fix bug preventing callbacks after unbind/bind when using scan jobs.

CHANGELOG.md, src/main/java/org/altbeacon/beacon/BeaconManager.java, src/main/java/org/altbeacon/beacon/service/BeaconService.java, src/main/java/org/altbeacon/beacon/service/ScanJob.java
Several changes to make the library behave properly when starting and stopping a foreground service on Android O+, and properly switching back to scan jobs when the foreground service is not active.
* Add a stopSelf() call when the last consumer is unbound from the scanning service to attempt to make service destruction (and force stopping scanning) more reliable.  Call stopForeground() before the call to stopSelf() to prevent a crash.
* Stop intent based scanning whenever stopping the ScanJob, so it is not left on (potentially launching  Scan Jobs again on detection even when the BeaconService is active in the foreground).
=> Make service stopping more reliable 

CHANGELOG.md, src/main/java/org/altbeacon/beacon/service/BeaconService.java, src/main/java/org/altbeacon/beacon/service/ScanHelper.java, src/main/java/org/altbeacon/beacon/service/ScanJob.java
This fixes the thread leak reported in #781 by terminating the ExecutorService threads used to parse beacon packets.  The thread termination now happens whenever the ScanJob or BeaconService is stopped.
=> Fix thread leak

CHANGELOG.md, src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScannerForLollipop.java
As reported in #769, when the screen on the Samsung Galaxy Note 9 w Android 8.1, scans stop.  The problem is reportedly fixed by adding a non-empty scan filter.  This change tests for that case (Android 8.1+ on a Samsung device) and adds a non-empty scan filter.
=> Fix broken Samsung screen off scans on 8.1+ 

CHANGELOG.md, lib/src/main/java/org/altbeacon/beacon/service/ScanHelper.java
ScanHelper Moving NPE exception above RuntimeException
=> ScanHelper Moving NPE exception above RuntimeException

lib/src/main/java/org/altbeacon/beacon/startup/RegionBootstrap.java
This is a follow on to #821, which added new constructors but inadvertently broke the original constructors by failing to set the monitorNotifier so callbacks would be issued.
=> Fix RegionBootstrap broken default consructors

CHANGELOG.md, lib/src/main/java/org/altbeacon/beacon/BeaconManager.java
This fixes a crash on starting scanning as a foreground service when there are more than one BeaconConsumers bound to BeaconManager.   Reported in #816
=> Fix crash on scanning as foreground service 

build.gradle, settings.gradle
Two changes to get release builds working:
Provides a project name for the lib folder so aar artifact gets named properly
Upgrades the jfrog plugin to work with latest gradle for binray uploads
=>  Fix buildscript for release builds and upload to jcenter

lib/src/main/java/org/altbeacon/beacon/BeaconManager.java
This commit will make sure that scheduled jobs are immediately cancelled upon calling setEnableScheduledJobs(false).  This resolves issue #845 as we were getting duplicate events after starting a foreground service.
=> Cancel scheduled jobs when setEnableScheduledJobs(false) is called

lib/src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScannerForLollipop.java
Resolves https://github.com/AltBeacon/android-beacon-library/issues/848
=> Only apply Samsung-specific non-empty scan filters when the screen is off

lib/src/main/java/org/altbeacon/beacon/service/ScanJob.java
This is an attempt to fix #814.  
@liloMoovel, can you please reproduce the issue with this library variant and see if it makes a difference?  You will need to compile off of this branch and make a binary build:
```
git clone https://github.com/AltBeacon/android-beacon-library.git
git checkout fix-restore-hang-on-ui-thread
./gradlew build
```
The above will produce a binary aar file in `lib/build/outputs/aar`.  You will then need to point your app's build.gradle file at that aar file instead of the version of this library in jcenter.
=> Move ScanJob startup work to non-UI thread in case of state restore hang

CHANGELOG.md, lib/src/main/java/org/altbeacon/beacon/BeaconManager.java
This fixes the thread leak described in #883
=> Fix thread leak caused by scheduling ScanJob when no consumers bound

lib/src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScanner.java
This attempts to fix #876, which reports a SecurityException crash when a library Alarm goes off after somebody switched users on the phone.  The fix is to detect the user switch and cancel the alarm.
Testing this on the Google Pixel 3a, I start the reference app (with a foreground service enabled), then switch to the Guest User.  I see that the logs show the alarm gets cancelled:
```
05-29 13:44:14.588  3760  3760 W CycledLeScanner: User switch detected.  Cancelling alarm to prevent potential crash.
05-29 13:44:14.588  3760  3760 D CycledLeScanner: cancel wakeup alarm: PendingIntent{b0fb482: android.os.BinderProxy@d3ba793}
05-29 13:44:14.600  3760  3760 D CycledLeScanner: Set a wakeup alarm to go off in 9223372035236175056 ms: PendingIntent{b0fb482: android.os.BinderProxy@d3ba793}
```
As …
=> Prevent crash on alarms going off with a different user active

CHANGELOG.md, lib/src/main/java/org/altbeacon/beacon/service/ScanJob.java, lib/src/main/java/org/altbeacon/beacon/service/ScanJobScheduler.java
This fixes an thread leak in an usual case where:
* ScanJobs are being used (default on Android 8+) AND
* 0 regions are being monitored and ranged, AND one of the following happens:
-  BeaconManager is used to apply a scanning settings change to the scanning service/job
-  BackgroundPowerSaver is active and the app switches foreground/background mode
The most likely way this could affect users of this library is by leaving BackgroundPowerSaver enabled on Android 8+ when the app is not ranging and monitoring any regions.
This happened because the ScanJob code failed to stop all the threads on CycledLeScanner by calling destroy() in the case where a ScanJob was abandoned because the BLE scan did not start.  And the BLE scan did not start (by design) if the number of regions monitored and …
=> Fix thread leak with 0 regions and settings applied

lib/src/main/java/org/altbeacon/bluetooth/BluetoothMedic.java
This PR adds a notification channel to be used in notifications posted by BluetoothMedic.
Posting notifications without a channel does not work on Android 8.0 and above
Expected Behavior:
When BluetoothMedic is used for power cycling bluetooth, on scan failures, and Medic notifications are enabled, when a scan failure occurs ,  bluetooth is power cycled and a notification is posted that says so.
Actual Behavior:
Bluetooth is power cycled, but no notification is posted.
If  Settings> developer options > Show Notification channel warnings is turned on, a warning toast message can be seen, .
Steps to reproduce:
1. Use the android beacon library reference app and enable BluetoothMedic power cycling and notifications in RangingActivity …
=>  Adding notification channel to support devices with Android 8.0 and above

CHANGELOG.md, lib/src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScannerForLollipop.java
This change is designed to solve the problem reported in #936 where a Samsung Device will be slow do detect a beacon (it will take an extra full scan period) if the app is put to the background with the screen on, then subsequently the screen goes off.
This is caused by the fact that an empty scan filter is set up when the app is pushed to the background, then disallowed by Samsung once the screen goes off.  The required non-empty screen off scan filter is not set up until the next scan cycle ends.
The solution is to start a BroadcastReceiver on Samsung devices for this case to look for screen off events before the next scan cycle starts.  If a screen off is detected, switch immediately to a non-empty scan filter.
This is a work in progress as I have not yet tested it on a Samsung device.
=> Expedite Samsung Screen Off Detections

CHANGELOG.md, lib/src/main/java/org/altbeacon/beacon/service/ScanJob.java
Fixes ConcurrentModificationException reported in #929
=> Fix crash caused by ConcurrentModificatonException from 929

lib/src/main/java/org/altbeacon/beacon/AltBeaconParser.java, lib/src/main/java/org/altbeacon/beacon/Beacon.java, lib/src/main/java/org/altbeacon/beacon/BeaconParser.java, lib/src/main/java/org/altbeacon/beacon/service/Callback.java, lib/src/main/java/org/altbeacon/beacon/service/RangedBeacon.java, lib/src/main/java/org/altbeacon/beacon/service/ScanHelper.java, lib/src/main/java/org/altbeacon/beacon/service/ScanJob.java, lib/src/main/java/org/altbeacon/beacon/service/ScanJobScheduler.java, lib/src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScanCallback.java, lib/src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScannerForJellyBeanMr2.java, lib/src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScannerForLollipop.java, lib/src/test/java/org/altbeacon/beacon/AltBeaconParserTest.java, lib/src/test/java/org/altbeacon/beacon/AltBeaconTest.java, lib/src/test/java/org/altbeacon/beacon/BeaconParserTest.java, lib/src/test/java/org/altbeacon/beacon/GattBeaconTest.java, lib/src/test/java/org/altbeacon/beacon/SBeaconTest.java, lib/src/test/java/org/altbeacon/beacon/org/altbeacon/beacon/simulator/BeaconSimulatorTest.java, lib/src/test/java/org/altbeacon/beacon/service/BeaconServiceTest.java
Allow to retrieve detection time, useful for background detections.
- Use `ScanResult::getTimestampNanos` and system clock/elapsedRealTime to compute epoch timestamp.
- Bring it from scan callbacks up to `Beacon` object in `mFirstCycleDetectionTimestamp` field and `mLastCycleDetectionTimestamp` which correspond respectively to the timestamp of the first and last detected packets.
Linked issue https://github.com/AltBeacon/android-beacon-library/issues/918
=> Bring detection timestamp up to beacon object

CHANGELOG.md, README.md, lib/src/main/java/org/altbeacon/beacon/BeaconParser.java, lib/src/main/java/org/altbeacon/beacon/service/scanner/ScanFilterUtils.java, lib/src/test/java/org/altbeacon/beacon/CBeaconTest.java
This updates the BeaconParser to be more flexible:
* Supports layouts based on GATT service advertisements without a matching beacon type code.   
* Makes the measured power field optional, and allows specifying a default measured power to use if it is absent.
The above changes are needed to more easily support  this format:
https://covid19-static.cdn-apple.com/applications/covid19/current/static/contact-tracing/pdf/ContactTracing-BluetoothSpecificationv1.1.pdf
=> Add support for covid beacon proposal from Apple and Google

lib/src/main/java/org/altbeacon/beacon/service/ScanState.java
ScanStateTest.serializationTest is failing on Windows with this error message: "E/ScanState: Error while saving scan status to file: Cannot rename temp file"
It is logged from the save method in ScanState when the temporary file (android-beacon-library-scan-state-temp) is renamed to the normal file (android-beacon-library-scan-state). 
The root cause seems to be this error message: "The process cannot access the file because it is being used by another process java.exe" which can be seen when you try to manually rename the file from Windows File System Explorer.
In order to reproduce, place a breakpoint before renameTo is called and then try to apply manual steps.
What I think is happening is that the java.exe process is locking the file because the stream resources are not closed so I …
=> Fix delete and rename scan state file on Windows

lib/src/main/java/org/altbeacon/beacon/BeaconManager.java
The background mode state is not preserved if the user wants to disable the monitoring explicitly in the background.
The background mode resets when unbinding the consumer.
Background flag should be maintained by the _BackgroundPowerSaver_ feature or explicitly by the user using _BeaconManager:setBackgroundMode_ method call.
The tests are passed (with fix #973).
Device: Huawei Mate 20 Pro
AndroidOS: 10
Debug without wire (over Wi-Fi)
Test case: enable monitoring in background:
1. **Before fix**
- This consumer is not bound.  Binding now: ...
- Activating background region monitoring
- Background region monitoring activated for region id1:
- Applying settings to ScanJob
- **Applying scan job settings with background mode false**
- Register calls: global=4 instance=4
- **Scheduling …
=> Remove background reset after unbind

CHANGELOG.md, lib/src/main/java/org/altbeacon/beacon/BeaconParser.java, lib/src/main/java/org/altbeacon/bluetooth/BleAdvertisement.java, lib/src/test/java/org/altbeacon/beacon/OverflowAreaBeaconTest.java, lib/src/test/java/org/altbeacon/bluetooth/BleAdvertisementTest.java
Makes scan result parsing more robust to detect beacon patterns in two cases that were not detected before:
* If multiple data types exist in the PDUs  (e.g. more than one FF manufacturer data type), try parsing every one of them to look for a match.
* If a scan response exists, parse the PDUs there as well.
The above changes allow detecting [overflow area advertisements](http://www.davidgyoungtech.com/2020/05/07/hacking-the-overflow-area) from iOS more reliably.  Unit tests cover two such cases.
=> Parse beacons from entirety of scan result including scan response

CHANGELOG.md, lib/src/main/java/org/altbeacon/bluetooth/BluetoothMedic.java
Fixes #980
Reproduced the problem by adding these lines to onCreate() of BeaconReferenceApplication:
```
Thread t = new Thread() {
public void run() {
try {
BluetoothMedic.getInstance();
}
catch (Exception e) {
Log.e(TAG, "Crash!", e);
System.exit(1);
}
}
};
t.start();
```
Before this fix, that crashed.  After this fix, it did not.
=> Fix BluetoothMedic crash when started on non-looper thread.

lib/src/main/java/org/altbeacon/beacon/BeaconManager.java, lib/src/main/java/org/altbeacon/beacon/service/BeaconService.java, lib/src/test/java/org/altbeacon/beacon/BeaconManagerTest.java
Closes https://github.com/AltBeacon/android-beacon-library/issues/990
> Long-running app may call "startRangingBeaconsInRegion" a significant number of times.
There's no internal check if such range is already present resulting in unlimited array growth.
=> Replace equals Regions on ranging beacons requests

README.md
In the README, JCenter was recently changed to Maven Central. This pull request updates the readme to reflect this change in other places.
=> Switch JCenter to Maven Central in Readme

README.md, build.gradle, lib/build.gradle
This reduces them minimum Android SDK version for using this library to 14.  
This had been unnecessarily increased to 21 in the 2.18 release.  I could have sworn that I was forced to do this by using a modern Android dependency, but when I went back to find it I could not.
=> Reduce min-sdk to 14. 

CHANGELOG.md, build.gradle, lib/build.gradle, lib/src/main/java/org/altbeacon/beacon/BeaconManager.java, lib/src/main/java/org/altbeacon/beacon/IntentHandler.java, lib/src/main/java/org/altbeacon/beacon/RegionViewModel.kt
This adds experimental LiveData support for beacon ranging and monitoring.  With this change, it is possible to do the following from a Kotlin Activity instead of using RangeNotifier and MonitorNotifier:
```
val monitoringObserver = Observer<Int> { state ->
var stateString = "inside"
if (state == MonitorNotifier.OUTSIDE) {
stateString == "outside"
}
Log.d(TAG, "monitoring state changed to : $stateString")
}
val rangingObserver = Observer<Collection<Beacon>> { beacons ->
Log.d(TAG, "Ranged: ${beacons.count()} beacons")
}
// These two lines set up a Live Data observer so this Activity can get beacon data from the Application class
val regionViewModel = BeaconManager.getInstanceForApplication(this).getRegionViewModel(region)
// observer will be called each time the monitored regionState …
```
=> Add Experimental LiveData support for ranging and monitoring

CHANGELOG.md, README.md, build.gradle, lib/build.gradle, lib/src/main/java/org/altbeacon/beacon/service/BeaconService.java, lib/src/main/java/org/altbeacon/beacon/utils/DozeDetector.java
This moves the `BeaconService` call to promote itself to a foreground service to the first line in `onCreate`.  This is done in an attempt to avoid crashes initiated by Android caused by the failure to promote a service to a foreground service within 5 seconds.  Such an exception looks like this:
```
android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{2ce3f6e u0 com.myapp/org.altbeacon.beacon.service.BeaconService}
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1801)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:210)
at android.app.ActivityThread.main(ActivityThread.java:7124)
at java.lang.reflect.Method.invoke(Method.java)
at …
```
=> Expedite foreground promotion

CHANGELOG.md, lib/src/main/java/org/altbeacon/beacon/BeaconManager.java, lib/src/main/java/org/altbeacon/beacon/IntentHandler.java, lib/src/main/java/org/altbeacon/beacon/Region.java, lib/src/main/java/org/altbeacon/beacon/service/Callback.java, lib/src/main/java/org/altbeacon/beacon/service/IntentScanStrategyCoordinator.kt, lib/src/main/java/org/altbeacon/beacon/service/MonitoringStatus.java, lib/src/main/java/org/altbeacon/beacon/service/RangeState.java, lib/src/main/java/org/altbeacon/beacon/service/ScanHelper.java, lib/src/main/java/org/altbeacon/beacon/service/ScanJob.java, lib/src/main/java/org/altbeacon/beacon/service/ScanJobScheduler.java, lib/src/main/java/org/altbeacon/beacon/service/scanner/ScanFilterUtils.java, lib/src/main/java/org/altbeacon/beacon/startup/StartupBroadcastReceiver.java, lib/src/test/java/org/altbeacon/beacon/service/scanner/ScanFilterUtilsTest.java
This is an experimental implementation of background scanning without a foreground service.
Generally on Android it is not possible to do regular BLE scanning without a long running service to host the timers.   And on Android 8+ this must be a foreground service.
However, Android 8+ does offer an alternative appropriate for some use cases.  You can do a constant BLE scan with matching results delivered by an Android Intent.  This will wake up a suspended app as needed to deliver the results.  There are, however, some limitations:
1. Beacon Ranging results cannot be delivered at regular intervals if bluetooth devices are not detected.  If no devices are detected, ranging callbacks will simply stop.
2. Similarly to the above, Beacon monitoring exit region results cannot be delivered …
=> Background beacon scanning without a foreground service

lib/src/main/AndroidManifest.xml, lib/src/main/java/org/altbeacon/beacon/BeaconParser.java, lib/src/main/java/org/altbeacon/beacon/service/BeaconService.java, lib/src/main/java/org/altbeacon/beacon/service/ScanHelper.java, lib/src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScanner.java, lib/src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScannerForLollipop.java, lib/src/main/java/org/altbeacon/bluetooth/BluetoothMedic.java
This builds on  #1040 by @nbadal to make a number of changes required to use the library with Android 12:
* All internal PendingIntents must specify FLAG_IMMUTABLE.
* All internal services and broadcast receivers in the library's Manifest must declare android:exported="false" 
* The library's automatic reading of the remote device's Bluetooth name must catch a SecurityException to prevent a crash in the case that the app does not have Manifest.permission.BLUETOOTH_CONNECT permission
This change does not add any permissions to the library's manifest, as it is unclear what is needed in the final version of Android 12.  Some of this may end up being documentation changes rather than library internal changes.
1. In my tests with Android 12 Build Number SPB3.210618.013, I was unable to get …
=> Android 12 Changes

build.gradle, lib/src/main/java/org/altbeacon/beacon/BeaconConsumer.java, lib/src/main/java/org/altbeacon/beacon/BeaconManager.java, lib/src/main/java/org/altbeacon/beacon/InternalBeaconConsumer.java, lib/src/main/java/org/altbeacon/beacon/powersave/BackgroundPowerSaver.java, lib/src/main/java/org/altbeacon/beacon/powersave/BackgroundPowerSaverInternal.java, lib/src/main/java/org/altbeacon/beacon/service/IntentScanStrategyCoordinator.kt, lib/src/main/java/org/altbeacon/beacon/service/ScanJobScheduler.java, lib/src/main/java/org/altbeacon/beacon/startup/BootstrapNotifier.java, lib/src/main/java/org/altbeacon/beacon/startup/RegionBootstrap.java
This marks several methods, classes and interfaces as deprecated in order to phase out manual calls to `bind()` and `BackgroundPowerSaver` that have long been causes of confusion and app bugs.  Replacement mechanisms are simpler, more intuitive and less error-prone.  
Backward compatibility is designed into this change, meaning apps using the discouraged APIs will see no impact other than deprecation warnings.
The impact of this change is documented [here](https://altbeacon.github.io/android-beacon-library/autobind.html)
=> Deprecate use bind() and associated methods and classes

lib/src/main/java/org/altbeacon/beacon/service/IntentScanStrategyCoordinator.kt
This fixes an Nullpointer Exception that can occur, if `adapter.getBluetoothLeScanner()` returns `null`. The code already checks if `scanner` is not null, but the Type Declaration does not allow that. For the change to work, callback had to be moved inside the if statement.
=> Fix NullPointerException in IntentScanStrategyCoordinator

CHANGELOG.md, lib/src/main/java/org/altbeacon/beacon/BeaconManager.java, lib/src/main/java/org/altbeacon/beacon/powersave/BackgroundPowerSaverInternal.java
The library uses a `BackgroundPowerSaver` class to track the activity lifecycle to determine if the app is in the foreground or background and apply configured scan periods depending on the background mode.  As of version 2.19, direct use of this class is deprecated and instead one is automatically created whenever `startMonitoring` or `startRangingBeacons` is first called.  
The problem with the above is that **we don't know the actual foreground/background state of the app when the user makes these calls.**  Android provides no APIs to determine the current foreground/background status of the app.  The preferred approach to doing this is to start tracking activities with the `Application.onCreate()` method.  But this library cannot guarantee that the first call to start monitoring or …
=> Improve default background mode with autobind

lib/build.gradle
This removes an unneeded declared dependency accidentally added in the 2.18 release when build scripts were reworked to  publish to Maven Central rather than JCenter.
The binary aar artifact does not include the incorrectly declared dependency `com.google.android.material:material:1.3.0`, so there is no practical impact on apps using library versions 2.18.x and 2.19 with this declaration.  
The only impact is that maven inaccurately reports this declared dependency in android-beacon-library-2.19.pom as reported in #1048.   Please ignore that declared dependency until this is corrected in the next release.
=> Remove unneeded android material dependency, accidentally added in 2.18

CHANGELOG.md, README.md, lib/src/main/java/org/altbeacon/beacon/service/ScanHelper.java
Fixes broken passive scans identified in #1058
The fix has been tested with the Kotlin reference app and `beaconManager.setIntentScanningStrategyEnabled(true)` and confirmed that beacons are detected on Android 10 and Android 12
This will be released imminently as 2.19.3
=> Fix broken intent scans

lib/build.gradle, lib/src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScanner.java
In addition to the existing permission checks for `ACCESS_FINE_LOCATION` and `ACCESS_COARSE_LOCATION`, the `CycledLeScanner` is allowed to start its scan when running on an Android 12 device that has been granted the new permission, `BLUETOOTH_SCAN`.
Resolves https://github.com/AltBeacon/android-beacon-library/issues/1063. The impact of this change can be verified from my forked version:
```
repositories {
jitpack()
}
dependencies {
// implementation("org.altbeacon:android-beacon-library:2.19.2")
implementation("com.github.mannodermaus:android-beacon-library:34b25a5e7a")
}
```
=> Add check for Android 12's BLUETOOTH_SCAN permission to CycledLeScanner

CHANGELOG.md, circle.yml, lib/src/main/java/org/altbeacon/beacon/BeaconManager.java, lib/src/main/java/org/altbeacon/beacon/BeaconParser.java, lib/src/main/java/org/altbeacon/beacon/logging/ApiTrackingLogger.kt, lib/src/main/java/org/altbeacon/beacon/logging/Loggers.java
This adds a ApiTrackingLogger which will keep track of all API calls in an internal array, allowing you to retrieve them at a later time.  This is intended to aid in debugging complex library initializations and lifecycle changes by telling you what API calls were made to the library and when.
Example Usage:
```
LogManager.setLogger(Loggers.apiTrackingLogger())
LogManager.setVerboseLoggingEnabled(true)
...
// Do this later on when you want to see what API calls were logged since library startup:
val apiCalls = Loggers.apiTrackingLogger().getApiCalls()
for (apiCall in apiCalls) {
Log.d(TAG, apiCall)
}
```
Sample results from starting the reference app.
```
2022-03-10 12:50:49.743 API getBeaconParsers, current count 1
2022-03-10 12:50:49.745 API getBeaconParsers, current count 0
2022-03-10 …
```
=> Add ApiTrackingLogger for troubleshooting complex setups

CHANGELOG.md, lib/src/main/java/org/altbeacon/beacon/BeaconManager.java, lib/src/main/java/org/altbeacon/beacon/service/ScanHelper.java, lib/src/main/java/org/altbeacon/beacon/service/SettingsData.java, lib/src/main/java/org/altbeacon/beacon/utils/ChangeAwareCopyOnWriteArrayList.kt
This fixes a number of bugs with the way the library applies settings to a running scan service, particularly BeaconParsers.   Prior to this change, apps using a Foreground Service that attempted to add or remove a new BeaconParser after scanning had already started, failed to do so, and race conditions could cause the BeaconParser list to be stuck with an empty list blocking detections.
After this change, configuration changes are automatically applied to a running service and the public API method. `beaconManager.applySettings()` can once again be used to force apply changes to running services. (Calling that method directly is not necessary as it is automatically called if needed when you make config changes.)
Since Android 8, the use of a Scanning Service usually only applies to a …
=> Fix bugs with changing BeaconParsers for running scan service

CHANGELOG.md, lib/src/main/java/org/altbeacon/beacon/BeaconManager.java, lib/src/main/java/org/altbeacon/beacon/service/MonitoringStatus.java, lib/src/main/java/org/altbeacon/beacon/service/RegionMonitoringState.java, lib/src/main/java/org/altbeacon/beacon/service/ScanState.java, lib/src/test/java/org/altbeacon/beacon/service/MonitoringStatusTest.java
This solves problems with persisted regions discussed in #1075. 
Problems prior to this change:
1. If you start monitoring a region and then change your app code to use a new Region uniqueId without stopping monitoring that old Region, the old Region is orphaned in library persistence and continues to be monitored forever.
2.  If you range a region, then change your app code to update the Region's identifiers but don't change the uniqueId, the old identifiers continue to be used.
This change fixes both problems.  
A few notes on how Monitored region persistence changes with this update:
1. Immediately after starting the app, if you call `beaconManager.getMonitoredRegions()` before starting monitoring, you will get an empty list.  You will not get the persisted list of regions.  (Prior to …
=> Fix region persistence usability problems

CHANGELOG.md, lib/src/main/java/org/altbeacon/beacon/BeaconManager.java, lib/src/main/java/org/altbeacon/beacon/powersave/BackgroundPowerSaverInternal.java, lib/src/main/java/org/altbeacon/beacon/service/BeaconService.java, lib/src/main/java/org/altbeacon/beacon/startup/StartupBroadcastReceiver.java
Apps using this library on Android 12 can crash if they configure the library's foreground service for scanning as reported in https://github.com/AltBeacon/android-beacon-library/issues/1082. This happens because Android 12 restricts when foreground services can be started to when:
The app is in the foreground
The app has received BOOT_COMPLETED
A number of other qualifying events (motion, Firebase messages, Bluetooth connect, etc.) not tracked by the library.
While it is possible to code around the above, the restrictions make it difficult to use the library. These following changes are designed to make using the library with a foreground service on Android 12 easier.
The library will detect if starting its foreground service fails, catching the exception and preventing a crash.
If the …
=> Handle Foreground Service Start Failures in Android 12

CHANGELOG.md, lib/src/main/java/org/altbeacon/beacon/service/BeaconService.java
This crash started showing up with Android 13 beta builds as reported in #1083.   It appears that a change in Android 13 alerts how null checks must be done for looking for Manifest metadata.
=> Fix Android 13 Crash 

CHANGELOG.md, lib/src/main/java/org/altbeacon/bluetooth/BluetoothMedic.java
- also removed unused broadcast notification code
This addresses the issue reported here: https://stackoverflow.com/questions/74709808/altbeacon-bluetoothmedic-crashes-with-android-version-12-13
This also deprecates the BluetoothMedic’s power cycling method in favor of a renamed legacy method that makes it clear that power cycling is no longer possible on Android 13 per #1109
=> Prevent crashes in BluetoothMedic from missing Android 12 permissions

lib/src/main/java/org/altbeacon/beacon/Beacon.java, lib/src/test/java/org/altbeacon/beacon/AltBeaconTest.java, lib/src/test/java/org/altbeacon/beacon/BeaconTest.java
When using `Beacon.Builder().copyBeaconFields()`, beacon's raw data is not copied in the new object. This PR fixes that and updates copyBeaconFields test cases.
=> Add lastPacketRawBytes when using copyBeaconFields

CHANGELOG.md, README.md, lib/build.gradle, lib/src/main/AndroidManifest.xml, lib/src/main/java/org/altbeacon/beacon/BeaconManager.java
This updates the library to support the upcoming Android 14 release, which imposes new restrictions on starting a foreground service.
This adds the necessary AndroidManifest.xml declarations for foreground services on Android 14, and also checks that `Manifest.permission.ACCESS_FINE_LOCATION` has been granted by the user in the call to `beaconManager.enableForegroundServiceScanning(...)`. If permission is not obtained when this call is made, the method now throws a `SecurityException` to let the user know this is a requirement.  
I have tested this on a Pixel 7 running Android 14 Beta 5 using a special branch of the Kotlin reference app and confirmed that the SecurityException crashes the app as described above before permission is granted, and it works to detect beacons with the …
=> Update foreground service support for Android 14 restrictions

lib/src/main/java/org/altbeacon/beacon/BeaconManager.java, lib/src/main/java/org/altbeacon/beacon/service/BeaconService.java
Hi David,
I have been doing some more experimentation with the library and targeting API 34.  I have two issues I would like to discuss.
1).  [In this commit](https://github.com/AltBeacon/android-beacon-library/commit/68f7320d1b9cfbc135c162fd0e8357b17bf830f0), you added logic to throw an exception when calling `enableForegroundServiceScanning()` without location permission.  I understand your reasoning for this but I was hoping we could move this check further down the chain.
The problem I ran into is that my application does things in a slightly different order.  One of the first things I do is configure the BeaconManager and call `enableForegroundServiceScanning()`.  I do this before I request location permission from the user.  In my app, the Beacons are an optional feature and I don't …
=> Additional Android 14 Improvements

CHANGELOG.md, lib/src/main/java/org/altbeacon/beacon/startup/StartupBroadcastReceiver.java
Android 14 introduced a change that restricts foreground service starts after BOOT_COMPLETED to only be allowed *after* the broadcast receiver event for BOOT_COMPLETED fires for the app.
Because of this, any app that tries to start beacon scanning with a foreground service enabled  from `Application.onCreate` will fail, and the library will detect this and fall back to using the Job Scheduler.   This did not happen on Android 12/13.  As of those OS versions, starting up a foreground service after boot from  `Application.onCreate` worked fine.
This change makes it so that the library will check for the previous failure to start the foreground service when handling the BOOT_COMPLETED event, and retry starting up the foreground service at that time.  
I tested this on a Pixel 7 / Android 14 …
=> Fix Android 14 foreground service start after BOOT_COMPLETED

lib/src/main/java/org/altbeacon/beacon/AltBeaconParser.java, lib/src/main/java/org/altbeacon/beacon/BeaconParser.java
Add back original/older method signatures which don't require the `timestampMs` field, to maintain backward compatibility with older closed-source clients which depend on android-beacon-library.
=> Backward compatibility - add 'fromScanData' to AltBeaconParser and BeaconParser

lib/src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScannerForLollipop.java
This appears to be necessary on a Pixel 7 running Android 14.   Is this real?  Tests in #1174 show that only the Pixel 7 (not the 6a) has this issue on Android 14.
I see no official mention of it.  Is this in the AOSP code, or is this a Pixel-specific change?  
Tests show that the app has to target Android 14 of the problem to come up (setting targetSdk to 33 will NOT cause the problem to show up on Android 14.)
=> Use scan filters on Android 14 when the screen is off

lib/src/main/java/org/altbeacon/beacon/BeaconManager.java, lib/src/main/java/org/altbeacon/beacon/service/RangedBeacon.java
Proposal fix for issue #1164
Proposal is to set default RSSI filter (RunningAverageRSSIFilter) in RangedBeacon class 
And use RunningAverageRSSIFilter as a fallback in case there is an issue during custom RSSI filter instantiation.
=> Fix get filter nullpointerexception

README.md, lib/src/main/java/org/altbeacon/beacon/BeaconManager.java, lib/src/main/java/org/altbeacon/beacon/distance/ModelSpecificDistanceCalculator.java
Two changes:
* Remove  the default model distance config URL that no longer works.  Library users can not specify their own URL.
* Change the storage mechanism for model distance JSON to be shared preferences so no permissions are needed to access storage on Android 14.
=> Fix bad model distance config url

README.md, lib/src/main/java/org/altbeacon/beacon/service/BeaconService.java, lib/src/main/java/org/altbeacon/beacon/service/ScanJob.java
Changes code to set  default distance calculator if a one has already been initialized.  This prevents overwriting a custom distance calculator class.
Fixes #1186
=> Fix distance calculator overwrite

CHANGELOG.md, lib/src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScannerForLollipop.java
A problem was reported in #1204, where Android 14 sometimes  failed to start a new scan with filters necessary to detect beacons with the screen off.  
This failure to start a scan has an error description indicating that the scan has already started (in fact, a similar scan without the filters has, so the code that checks for equality seems to be flawed in some way.)
The fix is to stop the scan before starting it if we believe a scan is already started.
After making this change I was unable to reproduce the problem using the same procedure from #1204.  However, since the problem was intermittent, I am not 100% confident this fixes anything.  Maybe I am just lucky in my tests with the fix?
=> Fix intermittent bug blocking screen off detections

CHANGELOG.md, lib/src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScannerForLollipop.java
This fixes a bug seen on non-Samsung phones with Android 14+ where a constant scan in the background at 100% duty cycle never starts a new scan, so never sets the scan filter required when the screen is off. 
The change registers a broadcast receiver on all devices with Andorid 14+ (not just Samsung) so that we switch to using the required non-empty scan filter when the screen goes off.
=> Fix scan failures when screen is off on Pixel phones

CHANGELOG.md, lib/src/main/java/org/altbeacon/beacon/BeaconManager.java
One of the problems with using the IntentScanStrategy is that you do not get rapid detections of region exits -- the only time the failure to detect your region is checked if no beacons are detected is when the ~15 minute scan job is called.
This change augments that a bit by forcing a re-calculation of region state whenever beaconManager.requestStateForRegion(...) is called and the IntentScanStrategy is active.  If you call that method periodically (or on an event of interest) and a beacon has not been seen in some time, an exit region event will fire.
=> Update region state on requestStateForRegion with IntentScanStrategy

CHANGELOG.md, lib/src/main/java/org/altbeacon/beacon/BeaconParser.java, lib/src/main/java/org/altbeacon/beacon/BeaconTransmitter.java, lib/src/main/java/org/altbeacon/beacon/service/scanner/ScanFilterUtils.java, lib/src/main/java/org/altbeacon/bluetooth/Pdu.java
This adds several improvements for beacon layouts based on GATT Service Advertisements
* Supports 128-bit service uuids with attached data
* Allows transmitting the above
* Uses data matching bytes in service UUID layouts inside Bluetooth filters
=> Improved support for GATT Service Advertisements

lib/build.gradle, lib/src/main/java/org/altbeacon/beacon/powersave/BackgroundPowerSaverInternal.java
The fix fixes the issue when we have the scan job restarting every time during navigation (activity opening) in the app.
Background mode - is set only if the user puts the app in the background or it keeps the background when startMonitoring was called in Application.onCreate during app start(as designed for background scanning).
Foreground mode - is set only one time when app become foreground. Fixed also an issue when starting activity is like the facade to find the proper starting activity to proceed app starting.
Fixes: https://github.com/AltBeacon/android-beacon-library/issues/1194
=> Fixed issue when scan job could restart every time when we have activity navigation

lib/src/main/java/org/altbeacon/beacon/powersave/BackgroundPowerSaverInternal.java
This pull request fixes an issue #1213 that was created after changing background state detection logic.
The function 'addObserver' should be called on main thread.  Otherwise, it made the app to crash in application where start ranging, monitoring beacons were called not from main thread.
=> [1213] Fixed crash when addObserver could be called not from main thread

CHANGELOG.md, lib/src/main/java/org/altbeacon/beacon/powersave/BackgroundPowerSaverInternal.java
An earlier change in #1195 altered the mechanism for monitoring background state, and the new mechanism can only be started up on the main thread otherwise the app crashes.  The consequence of this is that if you start monitoring or ranging on a background thread the app crashes.  
This fixes that by detecting if we are on a background thread, and if so, switching to the foreground thread before starting background monitoring.
Fixes #1213
=> Fix crash on background thead start of ranging or monitoring per #1213

CHANGELOG.md, lib/src/main/java/org/altbeacon/beacon/BeaconManager.java, lib/src/main/java/org/altbeacon/beacon/powersave/BackgroundPowerSaverInternal.java
As described in #1215 distance calculations are always returning -1.0 meters because the distance calculator is not being initialized in releases 2.20+
This fixes the above.
=> Fix absent distance calculator init
