AltBeacon/android-beacon-library

gradle/credentials.gradle

Fixed bintray user name

---

build.gradle

Sorry I keep screwing this up.

changed bintrayUser to bintrayUsername

---

README.md

Added the build status image from snap-ci

Added build status image.

---

src/main/java/org/altbeacon/beacon/service/BeaconService.java
src/main/java/org/altbeacon/beacon/service/CycledLeScanner.java
src/main/java/org/altbeacon/beacon/service/CycledLeScannerForJellyBeanMr2.java
src/main/java/org/altbeacon/beacon/service/CycledLeScannerForLollipop.java

As discussed in ticket #71
I couldn't test it properly on a L device, since I don't have one yet. However, I tried not to make changes to the logic, but only move things around, so everything should work.

Split old implementation and new implementation for CycledLeScanner

---

documentation.md
uses-feature.md

As discussed in #78 an explanation how to filter or include devices without Bluetooth support.

Explain uses-feature element to filter devices without Bluetooth LE

---

src/main/java/org/altbeacon/beacon/distance/ModelSpecificDistanceCalculator.java

fixes https://github.com/AltBeacon/android-beacon-library/issues/124

Suppress ModelSpecificDistanceCalculator error

---

src/main/java/org/altbeacon/beacon/BeaconManager.java

My old fix was not working with multiple consumer is bound at same time and also some of them is unbound before getting onBeaconServiceConnect event. I investigated code deeper this time, I saw you put synchronized blocks but it seems like those blocks does not working properly. No matter what I did except changing HashMap to ConcurrentHashMap, my use case was problematic. Actually, I don't know why ConcurrentModificationException occurs since synchronized blocks should already cover this problem.
BTW, I know my use case a little bit complicated since I need to bind multiple consumers and unbind them quickly still this can be a major issue for someone else too.

fix concurrency exception when multiple consumer bound on start

---

src/main/java/org/altbeacon/beacon/Identifier.java
src/test/java/org/altbeacon/beacon/IdentifierTest.java

For detailed reasoning about those changes, please see comments directly in the change view.
Feedback is requested. I'd supply more tests and docs once this receives general acceptance.
Fixes #150

Various improvements to Identifier, including UUID awareness

---

src/main/java/org/altbeacon/beacon/BeaconManager.java
src/main/java/org/altbeacon/beacon/service/ArmaRssiFilter.java
src/main/java/org/altbeacon/beacon/service/BeaconService.java
src/main/java/org/altbeacon/beacon/service/RangeState.java
src/main/java/org/altbeacon/beacon/service/RangedBeacon.java
src/main/java/org/altbeacon/beacon/service/RssiFilter.java
src/main/java/org/altbeacon/beacon/service/RunningAverageRssiFilter.java
src/test/java/org/altbeacon/beacon/service/ArmaRssiFilterTest.java
src/test/java/org/altbeacon/beacon/service/RunningAverageRssiFilterTest.java

RSSI Filter Implementation via Interfaces and Tracking Cache

Changes for #113 and #114

---

src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScanner.java

cut log spam by logging bluetooth off at debug level

---

src/main/java/org/altbeacon/beacon/BeaconTransmitter.java

catch exception if ble is off when stopping advertising

---

src/main/java/org/altbeacon/beacon/Beacon.java
src/main/java/org/altbeacon/beacon/BeaconConsumer.java
src/main/java/org/altbeacon/beacon/BeaconData.java
src/main/java/org/altbeacon/beacon/BeaconDataNotifier.java
src/main/java/org/altbeacon/beacon/BeaconIntentProcessor.java
src/main/java/org/altbeacon/beacon/BeaconManager.java
src/main/java/org/altbeacon/beacon/BeaconParser.java
src/main/java/org/altbeacon/beacon/BleNotAvailableException.java
src/main/java/org/altbeacon/beacon/MonitorNotifier.java
src/main/java/org/altbeacon/beacon/RangeNotifier.java
src/main/java/org/altbeacon/beacon/Region.java
src/main/java/org/altbeacon/beacon/client/BeaconDataFactory.java
src/main/java/org/altbeacon/beacon/client/DataProviderException.java
src/main/java/org/altbeacon/beacon/client/NullBeaconDataFactory.java
src/main/java/org/altbeacon/beacon/service/ArmaRssiFilter.java
src/main/java/org/altbeacon/beacon/service/BeaconService.java
src/main/java/org/altbeacon/beacon/service/Callback.java
src/main/java/org/altbeacon/beacon/service/MonitorState.java
src/main/java/org/altbeacon/beacon/service/MonitoringData.java
src/main/java/org/altbeacon/beacon/service/RangeState.java
src/main/java/org/altbeacon/beacon/service/RangedBeacon.java
src/main/java/org/altbeacon/beacon/service/RangingData.java
src/main/java/org/altbeacon/beacon/service/StartRMData.java
src/main/java/org/altbeacon/beacon/startup/BootstrapNotifier.java
src/main/java/org/altbeacon/beacon/startup/RegionBootstrap.java
src/main/java/org/altbeacon/beacon/startup/StartupBroadcastReceiver.java
src/main/java/org/altbeacon/bluetooth/BluetoothCrashResolver.java
src/test/java/org/altbeacon/beacon/AltBeaconTest.java

Should solve #155 
Majority of the changes here were done by doing `s/\t/    /` and `s/ +\n/\n/`, so nothing special. I also added and removed a few empty lines here and there I think.

Format code

---

backward-compatibility.md
beacon-transmitter-devices.md
beacon-transmitter.md
configure.md
distance-calculations.md
distance-triggering.md
download.md

A few spelling mistakes corrected.
Hope this is correct - my GitHub skills are minimal - no, non-existent.

Cosmetic changes only

---

src/main/java/org/altbeacon/beacon/AltBeacon.java
src/main/java/org/altbeacon/beacon/AltBeaconParser.java
src/main/java/org/altbeacon/beacon/Beacon.java
src/main/java/org/altbeacon/beacon/BeaconConsumer.java
src/main/java/org/altbeacon/beacon/BeaconManager.java
src/main/java/org/altbeacon/beacon/BeaconParser.java
src/main/java/org/altbeacon/beacon/BleNotAvailableException.java
src/main/java/org/altbeacon/beacon/distance/AndroidModel.java
src/main/java/org/altbeacon/beacon/distance/ModelSpecificDistanceCalculator.java
src/main/java/org/altbeacon/beacon/powersave/BackgroundPowerSaver.java
src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScanner.java
src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScannerForJellyBeanMr2.java
src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScannerForLollipop.java
src/main/java/org/altbeacon/beacon/startup/StartupBroadcastReceiver.java
src/main/java/org/altbeacon/bluetooth/BluetoothCrashResolver.java

Some cosmetic changes to the source, mostly in comments. Let me know if
you think this is useful.

Cosmetic changes

---

src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScannerForLollipop.java

This resolves a NullPointerException per #187

check for null on getBeaconAdapter

---

src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScanner.java

As reported in #184, the latest 5.x firmware from Samsung limits the number of Alarms to 500 per app launch.  This is an attempt to get around that limit by using a single `PendingIntent` for an Alarm, and rescheduling it whenever needed.

Avoid 500 alarm limit by rescheduling alarms

---

src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScannerForLollipop.java

This is an attempt to fix an intermittent Null Pointer Exception on the Galaxy Note 4 5.0.1 as reported in  #197

Attempt to fix NPE on Galaxy Note 4 5.0.1

---

src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScannerForLollipop.java

Protects against crashes of the beacon scanning service caused by an internal Android NPE exception.
Background:  Android 5.0 BLE scanning APIs sometimes throw a null pointer exception on some devices.  This appears to be a bug in the bluetooth stack on some Android 5.0 devices.  This has been reported here: https://code.google.com/p/android/issues/detail?id=160503
Until this bug is fixed, we must protect against an internal NPE whenever starting or stopping scanning with Android 5.0 BLE APIs.
This addresses #219

Catch NPE when starting/stopping scanning.  Android issue #160503

---

src/main/java/org/altbeacon/beacon/distance/ModelSpecificDistanceCalculator.java
src/test/java/org/altbeacon/beacon/distance/ModelSpecificDistanceCalculatorTest.java

Please merge this PR first: https://github.com/AltBeacon/android-beacon-library/pull/244
This is fix for java.util.ConcurrentModificationException
This is bug from production (Crashlitics)
```java
java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:299)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
at java.util.concurrent.FutureTask.run(FutureTask.java:239)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
at java.lang.Thread.run(Thread.java:841)
Caused by: java.util.ConcurrentModificationException
at …
```

Bugfix concurrent modification exception

---

src/main/java/org/altbeacon/beacon/Region.java
src/test/java/org/altbeacon/beacon/RegionTest.java

Adds ability to Range and Monitor by mac address per #253

Add mac address to Region

---

src/main/resources/model-distance-calculations.json
src/test/java/org/altbeacon/beacon/distance/ModelSpecificDistanceCalculatorTest.java
src/test/resources/model-distance-calculations.json

This implements feature request #325

Add distance caluclation for Moto X Pro 

---

src/main/java/org/altbeacon/beacon/Beacon.java
src/main/java/org/altbeacon/beacon/BeaconParser.java
src/main/java/org/altbeacon/beacon/service/BeaconService.java
src/main/java/org/altbeacon/beacon/service/ExtraDataBeaconTracker.java
src/main/java/org/altbeacon/beacon/service/GattBeaconTracker.java
src/test/java/org/altbeacon/beacon/service/ExtraDataBeaconTrackerTest.java

Related to issue #384 
Please review and comment with any changes. Thank you!

Better support for custom beacons with extra data advertisement packets

---

build.gradle

Addresses #332.  I am sorry to see this plugin go!

Remove SDK Plugin no longer compatible with latest Gradle plugin

---

src/main/resources/model-distance-calculations.json
src/test/resources/model-distance-calculations.json

Implement feature request #385

Add distance calculations for the Moto X 2nd gen XT1092

---

src/main/java/org/altbeacon/beacon/utils/eddystoneeid/EidResolver.java

- Removes an extra colon that causes an HTTP 400
Bad Request error when using an API key rather
than an OAuth token

Fix malformed JSON in EidResolver.java

---

circle.yml

Need to switch to Circle-CI from Snap-CI due to a problem with AAPT on Snap-CI Linux servers

add circle.yml for circle ci

---

src/main/java/org/altbeacon/beacon/BeaconManager.java
src/test/java/org/altbeacon/beacon/service/MonitoringStatusTest.java

Fixes inability to read mo itored regions restored from persisted store after an app restart, as described in #441

Access persisted monitors

---

CHANGELOG.md
src/main/java/org/altbeacon/beacon/BeaconManager.java
src/main/java/org/altbeacon/beacon/service/DetectionTracker.java
src/main/java/org/altbeacon/beacon/service/MonitoringStatus.java
src/main/java/org/altbeacon/beacon/service/Stats.java

This fixes possible race conditions creating the singleton instances of:
- `BeaconManager`
- `DetectionTracker`
- `MonitoringStatus`
- `Stats`
Both `DetectionTracker` and `Stats` require no argument to their constructors. The singleton instances are also both `private` to the class. This means we can create the singleton instance as a constant without worry about any additional threading issues; Java guarantees constant creation thread safety (see _Effective Java_, Second Edition, _Item 3: Enforce the singleton property with a private constructor or an enum type_).
However, both `BeaconManager` and `MonitoringStatus` require the application context in order to be created. This means we cannot use a constant since we won't have the application context instance available at constant …

Ensure singleton object creation thread safety

---

src/main/java/org/altbeacon/beacon/service/ScanHelper.java

Fixes https://github.com/AltBeacon/android-beacon-library/issues/561

Fix NPE in ScanJob on Android O while bluetooth is turned off

---

CHANGELOG.md

Updates changelog for modifications to be included in 2.12.2.

Prepare for 2.12.2 release

---

CHANGELOG.md
src/main/java/org/altbeacon/beacon/utils/ProcessUtils.java

Protect against NPE on process util process check

---

CHANGELOG.md
src/main/java/org/altbeacon/beacon/service/ScanJob.java

Fix NPE in #616 by reworking initialization

Fix NPE on extra beacon data tracker

---

src/main/java/org/altbeacon/beacon/service/ExtraDataBeaconTracker.java
src/main/java/org/altbeacon/beacon/service/ScanHelper.java
src/test/java/org/altbeacon/beacon/service/ExtraDataBeaconTrackerTest.java

This adds annotations to `ExtraDataBeaconTracker` and it's use within `ScanHelper`. This came about after reviewing #617 and #626. While trying to understand how `ExtraDataBeaconTracker` was processing the beacons I ended up re-arranging some of the code to flatten the conditionals and reduce the number of branches I had to track mentally resulting in a minor refactor. This also lead to noticing that the setting of the tracked beacon extra data wasn't tested, so the tests were updated to check this.

Minor refactor and annotation updates

---

CHANGELOG.md

Prepare for release 2.13

---

CHANGELOG.md
src/main/AndroidManifest.xml

Fix crash from incorrect metadata name 

---

README.md
build.gradle

Fix javadoc generation so it uses Doclava and doesn't fail

Fix javadoc generation

---

src/main/java/org/altbeacon/beacon/BeaconManager.java

Invert conditional logic for logging "disable ScanJob" warning

---

CHANGELOG.md
src/main/java/org/altbeacon/beacon/service/BeaconService.java
src/main/java/org/altbeacon/beacon/service/ScanHelper.java
src/main/java/org/altbeacon/beacon/service/ScanJob.java

Fixes  crash issue reported in #758.  This is a side effect of the attempted  fix in #724.

Fix NPE on cycled le scanner

---

CHANGELOG.md
src/main/java/org/altbeacon/beacon/service/BeaconService.java

This fixes reversed logic preventing proper cleanup during service shutdown.

Properly cleanup service after shutdown

---

CHANGELOG.md
lib/src/main/java/org/altbeacon/beacon/service/ScanJob.java
lib/src/main/java/org/altbeacon/beacon/service/ScanJobScheduler.java

Attempt to address problem in #836

Fix failed callbacks by registering local broadcast receiver earlier

---

CHANGELOG.md
lib/src/main/java/org/altbeacon/beacon/service/ScanJob.java

Protect against NPE on failed restore of ScanState

---

CHANGELOG.md
lib/src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScanner.java

Fix IllegalArgumentException from ending user switch watching

---

download.md

Fixed typo

---

CHANGELOG.md
lib/src/main/AndroidManifest.xml

Fix the manifest service declarations as required for Android 12 as described in #1029

Fix service declarations for Android 12

---

CHANGELOG.md
lib/src/main/java/org/altbeacon/beacon/service/ScanJob.java

Fix failure to start scan job 

---

CHANGELOG.md
lib/src/main/java/org/altbeacon/beacon/Beacon.java
lib/src/main/java/org/altbeacon/beacon/BeaconParser.java
lib/src/main/java/org/altbeacon/beacon/service/ScanHelper.java
lib/src/main/java/org/altbeacon/beacon/service/ScanState.java
lib/src/main/java/org/altbeacon/bluetooth/Pdu.java
lib/src/test/java/org/altbeacon/beacon/AltBeaconTest.java
lib/src/test/java/org/altbeacon/beacon/BeaconParserTest.java

* Exposes raw bytes of beacon, useful for troubleshooting purposes
* Accept AD type 7 for 128 bit service UUID beacon detections

Expose raw bytes of beacon and accept AD type 0x07

---

CHANGELOG.md
lib/build.gradle
lib/src/main/java/org/altbeacon/beacon/Beacon.java
lib/src/main/java/org/altbeacon/beacon/BeaconManager.java
lib/src/main/java/org/altbeacon/beacon/BeaconParser.java
lib/src/main/java/org/altbeacon/beacon/BeaconRegion.kt
lib/src/main/java/org/altbeacon/beacon/Identifier.java
lib/src/main/java/org/altbeacon/beacon/Region.java
lib/src/main/java/org/altbeacon/beacon/Settings.kt
lib/src/main/java/org/altbeacon/beacon/distance/DistanceCalculatorFactory.kt
lib/src/main/java/org/altbeacon/beacon/distance/ModelSpecificDistanceCalculatorFactory.kt
lib/src/main/java/org/altbeacon/beacon/service/BeaconService.java
lib/src/main/java/org/altbeacon/beacon/service/IntentScanStrategyCoordinator.kt
lib/src/main/java/org/altbeacon/beacon/service/ScanJob.java
lib/src/test/java/org/altbeacon/beacon/SettingsJavaTest.java
lib/src/test/java/org/altbeacon/beacon/SettingsTest.kt

This working branch implements the new Settings and BeaconRegion configuration APIs that are planned for 
The new APIs are expected to live alongside the old APIS for future 2.x releases of the library
Only the new APIs will exist in the 3.0+ versions of the library
See #1061 for design details

New Configuration API for 3.0

---

CHANGELOG.md
lib/src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScanner.java

Reduce max scan interval from 30 min to 10 min to fix droputs

---

CHANGELOG.md
lib/src/main/java/org/altbeacon/beacon/BeaconManager.java
lib/src/main/java/org/altbeacon/beacon/Settings.kt
lib/src/main/java/org/altbeacon/beacon/service/BeaconService.java
lib/src/main/java/org/altbeacon/beacon/service/IntentScanStrategyCoordinator.kt
lib/src/main/java/org/altbeacon/bluetooth/BluetoothMedic.java

Fix broken longScanForcingEnabled on new settings api

---

lib/src/main/java/org/altbeacon/beacon/BeaconManager.java
lib/src/main/java/org/altbeacon/beacon/Settings.kt

Fixes the issue reported here: https://github.com/AltBeacon/android-beacon-library/issues/1221

ISSUE#1221: Use correct scanning parameters for bg scan
